### ISSUE TITLE
Find and replace issue with "Only in selection" enabled

### ISSUE THREAD

**Issue by RafaelLinux** [atom/find-and-replace#942] opened 2017-08-17 21:48 UTC
v1.20 beta 3 on OpenSUSE

I have enabled “Finding with Options: Regex, Case Insensitive, Within Current Selection” and want to select parts of actual text to do the same search and replace. The result are like expected, however, the interface is not working fine. Resume:

1. Having a text selected, first time I click on “Replace all”, it works fine. However, when I select a new block of text and try to click again in “Replace all”, that button is like “greyed” and nothing happens till I toggle on and off any of the options for finding, but that have another issue, then next point:
2.  A selected text, is deselected each time I toggle “Options” buttons for “Find and replace” (like “Regex” or “Case Insensitive”), despite I have “In selected text” enabled

**Comment by lee-dohm** [comment] 2017-08-17 21:58
Item 1 is the expected behavior. In order to replace things, you have to execute a Find first. So Replace is expected to be grayed out when you change the selection.

Item 2 is a duplicate of https://github.com/atom/find-and-replace/issues/631. You may want to subscribe there for updates.

In the future:

1. Please use the issue template to ensure that we get all the information that we need
1. Follow the [Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) and search for your issue first

Both of these save the maintainers time which allows us to work on making Atom better.

**Closed by lee-dohm** 2017-08-17 21:58 UTC

**Comment by RafaelLinux** [comment] 2017-08-17 23:07
Despite you closed this issue cause you have a different point of view, IMHO, the Item 1 simplify to user any repetitive task of search&replace. The way is working now, user (that can see exactly what is selecting) know that the s&r function have a task to do for sure, so click "Replace all" is the fastest way to do what he need.
Is not a extrange way of work. I used previously Kate (Plasma) and worked this way always without problems, without requiring a previous "find" even selecting distinct parts of text.

Thank you anyway

**Comment by roman-sitewits** [comment] 2020-11-10 07:19
This is so not fixed

**Comment by RafaelLinux** [comment] 2020-11-11 00:13
Agree
