### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by tiagomacarios** [atom/find-and-replace#812] opened 2016-11-16 03:50 UTC
[Enter steps to reproduce below:]

Apparently this happens if I create a capture group by starting with the last parenthesis.

**Atom Version**: 1.13.0-beta2
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.204.2

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /\d) blah_/: Unmatched ')'

```
At C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\find-and-replace\lib\find-options.js:82

SyntaxError: Invalid regular expression: /\d) SPECTRUM_/: Unmatched ')'
    at RegExp (native)
    at FindOptions.module.exports.FindOptions.getFindPatternRegex (C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\find-and-replace\lib\find-options.js:82:14)
    at BufferSearch.module.exports.BufferSearch.doesMatchTheEmptyString (C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:105:31)
    at FindView.module.exports.FindView.liveSearch (C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\find-and-replace\lib\find-view.js:436:139)
    at C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\find-and-replace\lib\find-view.js:343:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at C:\Users\tmc\AppData\Local\atom\app-1.13.0-beta2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1417:25
```

### Commands

```
     -2:53.1.0 core:backspace (input.hidden-input)
     -2:52.9.0 editor:newline (input.hidden-input)
     -2:52 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:51.6.0 editor:newline (input.hidden-input)
     -2:42.1.0 core:paste (input.hidden-input)
  2x -2:40.7.0 editor:move-to-first-character-of-line (input.hidden-input)
  4x -2:37.1.0 core:move-left (input.hidden-input)
     -2:24.9.0 core:undo (input.hidden-input)
     -0:45.1.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:42.2.0 core:move-up (input.hidden-input)
  2x -0:41.2.0 core:move-down (input.hidden-input)
     -0:36.1.0 core:backspace (input.hidden-input)
     -0:33.4.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:11.2.0 core:undo (input.hidden-input)
     -0:07.1.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:06.4.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.11 (active)
highlight-selected, v0.11.2 (active)
language-cmake, v0.2.0 (active)
language-qs, v0.0.1 (active)
language-restructuredtext, v1.0.1 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.3 (active)
rst-preview-pandoc, v0.1.12 (active)
script, v3.11.1 (inactive)
sort-lines, v0.14.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-11-16 19:11
I'm seeing this as well, it's pretty simple to reproduce: Just put in invalid Regex (`Commit (` in my case)

----

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0-beta3
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.204.2


### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /Commit(/: Unterminated group

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\find-and-replace\lib\find-options.js:82

SyntaxError: Invalid regular expression: /Commit(/: Unterminated group
    at RegExp (native)
    at FindOptions.module.exports.FindOptions.getFindPatternRegex (C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\find-and-replace\lib\find-options.js:82:14)
    at BufferSearch.module.exports.BufferSearch.doesMatchTheEmptyString (C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:105:31)
    at FindView.module.exports.FindView.liveSearch (C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\find-and-replace\lib\find-view.js:436:139)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\find-and-replace\lib\find-view.js:343:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1417:25
```

### Commands

```
     -0:38.7.0 editor:select-to-end-of-word (input.hidden-input)
  2x -0:38.2.0 core:select-left (input.hidden-input)
  9x -0:37.6.0 intentions:highlight (input.hidden-input)
     -0:36.8.0 core:copy (input.hidden-input)
     -0:35.8.0 intentions:highlight (input.hidden-input)
     -0:35.7.0 core:save (input.hidden-input)
     -0:20.3.0 intentions:highlight (input.hidden-input)
     -0:20.1.0 core:paste (input.hidden-input)
     -0:16.5.0 intentions:highlight (input.hidden-input)
     -0:16 core:save (input.hidden-input)
     -0:06.6.0 intentions:highlight (input.hidden-input)
     -0:06.4.0 find-and-replace:show (input.hidden-input)
     -0:04.5.0 core:move-right (input.hidden-input)
  3x -0:03.9.0 core:move-up (input.hidden-input)
  8x -0:02.1.0 core:move-down (input.hidden-input)
     -0:00.4.0 core:move-up (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-gjslint",
      "language-chef",
      "linter-pep8",
      "svn",
      "linter-csslint",
      "linter-pylint",
      "flow-ide",
      "linter-perl",
      "linter-jscs",
      "language-babel",
      "linter-phpmd",
      "linter-pylama",
      "atom-typescript"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "find-and-replace": {
    "openProjectFindResultsInRightPane": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.20.2 (active)
atom-beautify, v0.29.13 (active)
atom-typescript, v10.1.12 (inactive)
autocomplete-python, v1.8.12 (active)
busy-signal, v1.2.0 (active)
docblockr, v0.8.7 (active)
editorconfig, v2.0.5 (active)
file-watcher, v0.4.0 (active)
flow-ide, v1.1.9 (inactive)
highlight-selected, v0.11.2 (active)
intentions, v1.1.2 (active)
language-babel, v2.49.2 (inactive)
language-chef, v0.9.0 (inactive)
language-cjson, v0.0.1 (active)
language-docker, v1.1.7 (active)
language-elixir, v0.16.0 (active)
language-fortran, v2.0.15 (inactive)
language-glsl, v2.0.1 (active)
language-haml, v0.24.1 (active)
language-ini, v1.16.0 (active)
language-postcss, v1.3.0 (active)
language-powershell, v4.0.0 (active)
language-puppet, v0.21.0 (active)
language-r, v0.4.1 (active)
language-reg, v0.0.0 (active)
linter, v1.11.4 (active)
linter-alex, v3.2.0 (active)
linter-coffeelint, v1.2.0 (active)
linter-csslint, v1.3.3 (inactive)
linter-eslint, v8.0.0 (active)
linter-flake8, v2.0.2 (active)
linter-htmlhint, v1.3.1 (active)
linter-js-yaml, v1.2.5 (active)
linter-jsonlint, v1.3.0 (active)
linter-markdown, v3.0.2 (active)
linter-perl, v0.8.0 (inactive)
linter-perlcritic, v1.2.3 (active)
linter-php, v1.3.1 (active)
linter-phpcs, v1.5.3 (active)
linter-phpmd, v1.5.2 (inactive)
linter-proselint, v3.2.0 (active)
linter-pylama, v0.8.6 (inactive)
linter-pylint, v1.2.2 (inactive)
linter-rails-best-practices, v0.2.2 (active)
linter-reek, v2.1.5 (active)
linter-rubocop, v0.5.0 (active)
linter-ruby, v1.2.2 (active)
linter-stylelint, v3.5.0 (active)
linter-tidy, v2.3.0 (active)
linter-ui-default, v0.0.3 (active)
mapfile-grammar, v0.1.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.3 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-selection, v4.4.0 (active)
pigments, v0.38.0 (active)
sequential-number, v0.4.0 (inactive)
seti-syntax, v1.0.1 (active)
seti-ui, v1.3.2 (active)
sort-lines, v0.14.0 (inactive)
Stylus, v3.1.0 (active)
svn, v0.0.13 (inactive)
tab-control, v0.6.9 (active)
toggle-quotes, v1.0.0 (inactive)
trailing-spaces, v0.3.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-11-16 21:19
This is a duplicate of #809 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-11-16 21:19 UTC
Labels: needs-reproduction
