### ISSUE TITLE
^[^0-9].*[\r\n]+ selects every other line

### ISSUE THREAD

**Issue by tiniba** [atom/find-and-replace#804] opened 2016-10-31 18:15 UTC
`^[^0-9].*[\r\n]+`

this expression should select everything that does not start with numbers, but it ends up selecting odd numbers.

**Comment by 50Wliu** [comment] 2016-10-31 20:57
No, it's actually selecting every other line.
![every-other-line](https://cloud.githubusercontent.com/assets/2766036/19871396/19a7b602-9f8b-11e6-94b8-b4e2b0c77458.png)

**Comment by tiniba** [comment] 2016-11-01 15:40
see example below tested in the following editors (Notepad ++, UltraEdit, Sublime):

https://regex101.com/r/C2IQre/1

**Comment by 50Wliu** [comment] 2016-11-01 15:52
Yes, I realize what it's intended to do, I'm just saying what you're observing in Atom is not what I'm seeing.  Can you confirm that behavior?

**Comment by tiniba** [comment] 2016-11-01 16:10
Bug http://imgur.com/LYUdGRL

Verison windows: http://imgur.com/a/O4EvA

**Comment by 50Wliu** [comment] 2016-11-01 17:17
Yes.  What I'm saying is, can you please try my example and see what happens?

**Comment by tiniba** [comment] 2016-11-01 18:09
it is?

http://imgur.com/a/Mc42d

**Comment by Ephphatha** [comment] 2016-11-02 23:48
This bug appears to be a duplicate of #780, and is due to the start of line anchor allowing matches to begin between the CRLF characters for files with windows style line endings. To get the desired behaviour the line endings need to be changed to LF only or the regex updated to ^[^0-9\n].*\r?\n

**Comment by 50Wliu** [comment] 2016-11-03 00:12
Thanks @Ephphatha.

**Closed by 50Wliu** 2016-11-03 00:12 UTC
Labels: bug
