### ISSUE TITLE
RegExp too big

### ISSUE THREAD

**Issue by nnenadovic** [atom/find-and-replace#587] opened 2015-11-05 16:56 UTC
: RegExp too big
  at RegExp.exec (native)
  at Forwards.next (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/match-iterator.js:15:30)
  at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:861:31)
  at TextEditor.module.exports.TextEditor.scanInBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:2067:26)
  at BufferSearch.module.exports.BufferSearch.createMarkers (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:155:23)
  at BufferSearch.module.exports.BufferSearch.bufferStoppedChanging (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:221:27)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1276:25

**Comment by 50Wliu** [comment] 2015-11-05 17:08
Duplicate of #510, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-05 17:08 UTC
