### ISSUE TITLE
Regex find highlights correctly, but Replace-All does nothing

### ISSUE THREAD

**Issue by lope** [atom/find-and-replace#866] opened 2017-02-24 14:31 UTC
sample text
`"foo": 1`

Regex search: `"(?=[a-zA-Z]+":)`
Replace: whatever

1 result found for (regex) but Replace All does nothing.
I copy pasted the sample string and regex into gedit. It had the same problem.
Then I used Regex101.com and it's substitution worked.

**Comment by 50Wliu** [comment] 2017-02-24 16:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #299. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-24 16:38 UTC
