### ISSUE TITLE
Handle 'Use Selection From Find' from other apps

### ISSUE THREAD

**Issue by sandstrom** [atom/find-and-replace#733] opened 2016-05-26 16:12 UTC
### Description

In OS X most programs can use cmd + e to copy the selected text into the page-search (*Use selection for find*). I.e. selecting the text 'dog', pressing cmd + e and then cmd + g (or cmd + f) will search the document for for 'dog'.

What's more, this works across applications. One can select text in TextEdit, use cmd + e and then search in Chrome, Terminal etc.

While Atom supports cmd + e, cmd + g etc. it doesn't get/retrieve a value set by cmd + e in another program.

### Steps to Reproduce

1. Open TextEdit
2. Select a string of text, e.g. 'last'
3. Press `cmd + e`
4. Open Terminal
5. Press `cmd + g` (it will search for 'last')
6. Open Atom
7. Press `cmd + g` (it won't search for 'last')

**Expected behavior:**

It will search for 'last'.

**Actual behavior:**

It won't search for 'last'.

### Versions

```
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by 50Wliu** [comment] 2016-05-26 20:34
This is a duplicate of atom/atom#4650 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-26 20:34 UTC

**Comment by sandstrom** [comment] 2016-05-26 21:15
Got it! Thanks! 

*(I did search that repo too, but couldn't find an open issue, sorry!)*
