### ISSUE TITLE
Custom commands do not work well with replacement input area

### ISSUE THREAD

**Issue by hitobashira** [atom/find-and-replace#749] opened 2016-06-25 17:59 UTC
Custom commands do not work well with replacement input area . Resulting in work in the area of ​​the text editor .

For example, the following command (for example )

**init.coffee**
atom.commands.add 'atom-text-editor', 'custom:cut-line2', ->
  editor = atom.workspace.getActiveTextEditor()
  editor.selectLinesContainingCursors()
  editor.cutSelectedText()

**keymap.cson**
'atom-workspace atom-text-editor':
#TEST command
  'alt-k': 'custom:cut-line2'

1.  launch find and replace , and some strings. 
2. edit the target string .....with not core comannd such as core:cut.
3. alt-k (custom:cut-line2)
4.  the text editor area is cut ....

How do you do a workaround .

**Comment by Ben3eeE** [comment] 2016-07-06 07:11
Since this is just a question about making custom commands it is probably more suited for posting on https://discuss.atom.io where you are likely to get help faster.

This is also a duplicate of https://github.com/atom/atom/issues/12051 just executed from a different place so undefined is not returned.

**Comment by 50Wliu** [comment] 2016-07-15 12:03
Thanks @Ben3eeE.

**Closed by 50Wliu** 2016-07-15 12:03 UTC
