### ISSUE TITLE
New search doesn't clear out old searches.

### ISSUE THREAD

**Issue by drdreads** [atom/find-and-replace#448] opened 2015-07-14 17:12 UTC
It would be really nice if when searching, there was an option to display the results in a new pane/view so that the old results did not get clobbered by the new search results.

label:enhancement

**Comment by bronson** [comment] 2015-07-24 01:30
Pretty sure this is a dupe of #360

**Comment by 50Wliu** [comment] 2015-07-24 14:00
Thanks @bronson!

**Closed by 50Wliu** 2015-07-24 14:00 UTC
