### ISSUE TITLE
Uncaught TypeError: Cannot read property 'matches' of undefined

### ISSUE THREAD

**Issue by btstw** [atom/find-and-replace#883] opened 2017-04-14 09:48 UTC
[Enter steps to reproduce:]

1. Using Project Find, search for some text that doesn't exist in the project so you get no results back.
2. Press the down arrow key

Reproduces in safe mode as well.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.207.3

### Stack Trace

Uncaught TypeError: Cannot read property 'matches' of undefined

```
At C:\Users\MISUser\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\find-and-replace\lib\project\results-view.js:308

TypeError: Cannot read property 'matches' of undefined
    at ResultsView.moveDown (/app.asar/node_modules/find-and-replace/lib/project/results-view.js:308:49)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
 61x -5:57.7.0 core:move-down (div.results-view.focusable-panel)
  2x -5:27.4.0 core:move-up (input.hidden-input)
 10x -5:26.5.0 core:move-down (input.hidden-input)
  7x -4:46.2.0 core:move-up (div.results-view.focusable-panel)
  2x -4:43.3.0 core:move-down (div.results-view.focusable-panel)
     -4:33.8.0 find-and-replace:show (input.hidden-input)
     -4:31.7.0 project-find:show (input.hidden-input)
     -4:28.4.0 core:backspace (input.hidden-input)
  3x -4:24.7.0 core:move-right (input.hidden-input)
  3x -4:23.1.0 core:move-left (input.hidden-input)
     -4:22.2.0 core:backspace (input.hidden-input)
     -4:21.2.0 core:confirm (input.hidden-input)
  4x -4:19.3.0 core:move-down (div.results-view.focusable-panel)
     -0:07.9.0 core:move-up (input.hidden-input)
     -0:07.2.0 core:confirm (input.hidden-input)
     -0:06.2.0 core:move-down (div.results-view.focusable-panel)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-beautify 0.29.18 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-runner 2.7.1 
busy-signal 1.3.0 
color-picker 2.2.5 
file-icons 2.1.2 
goto-definition 1.3.1 
gpp-compiler 3.0.7 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
js-refactor 0.7.5 
linter 2.1.2 
linter-gcc 0.7.1 
linter-htmlhint 1.3.3 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.2 
pigments 0.39.1 
project-manager 3.3.4 
refactor 0.11.4 
Remote-FTP 0.10.7 
sass-autocompile 0.13.3 
scroll-searcher 5.2.0 
simple-drag-drop-text 0.3.4 
sync-settings 0.8.1 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
trailing-spaces 0.4.0 
```

Use Project Find to search text that doesn't exist and press arrow down key get this error.

Reproduced on Windows 10 and macOS 10.12.3.

**Comment by rsese** [comment] 2017-04-14 17:32
I can reproduce on 1.16.0 on Windows 10 and macOS 10.12.3, thanks for the report!  I went ahead and added your steps to reproduce to that section in the issue body and added more OS details.

**Comment by Ben3eeE** [comment] 2017-04-15 12:43
@rsese this is a  duplicate of https://github.com/atom/atom/issues/14017. Fixed in 1.17?
/cc: @iolsen we should really look over the regression project.

**Comment by rsese** [comment] 2017-04-17 05:39
Ahhh, thanks for the pointer @Ben3eeE not sure how I missed that one :bow:

**Closed by rsese** 2017-04-17 05:39 UTC
Labels: bug, triaged, uncaught-exception

**Comment by odahcam** [comment] 2017-04-27 17:36
Reproduced on Mac 10.12.4 Sierra.

**Comment by Gasuleg** [comment] 2017-06-09 07:55
Reproduced on Debian 8
