### ISSUE TITLE
Replace doesn't work properly when lookarounds are used

### ISSUE THREAD

**Issue by nemonein** [atom/find-and-replace#630] opened 2016-01-02 06:19 UTC
- OS: Ubuntu 14.04 (64bit)
- Atom version: 1.3.2 

for 1234567890,

> Find (in Buffer): \d(?=(?:\d{3})+(?!\d)) (Regex)
> Replace : $&,

It shoud replace 1234567890 to 1,234,567,890, but nothing happens.

Another Example,
for 1234567890,

> Find (in Buffer): \d(?=(?:\d{3})+(?!\d)) (Regex)
> Replace : 123

No replacement at all, either.

I think when Regex Lookarounds are used, there might be some malfunction on the replace logic.

**Comment by davidpaulhunt** [comment] 2016-02-18 20:55
I'm having the same issue.

Example: Using `\n^\s*\,` finds the correct new lines, spaces, and commas. But replaces nothing regardless of what I put into the replace field.

```js
app.put('/some/:route.:format?',
  provides(null,
    middleware(someVar)
  , middleware2({ required: true })
  , largerMiddleware({
      'param': { type: 'string', required: true }
    , 'param': { type: 'string', required: true }
    })
  , foo.Middleware.index  )
);
```

**Comment by lee-dohm** [comment] 2016-02-18 21:09
@nemonein Currently the find-and-replace package uses JavaScript regular expressions which, to my knowledge, don't support lookarounds.

@davidpaulhunt What you're referencing I believe is a special case of #218.

**Comment by sabrehagen** [comment] 2017-04-05 12:48
I'm experiencing this too when using regex search. I'm trying to remove all semicolons from the end of lines. My find criteria is `;$` and my replace criteria is empty. Whenever I click replace all atom reloads the search results but doesn't make any replacements. No errors are shown in the console.

Atom 1.12.7

**Comment by lee-dohm** [comment] 2017-04-05 16:20
@sabrehagen Please update to the latest version of Atom and open a new Issue. Since you're describing find-in-project behavior, the problem you're describing isn't related.

**Comment by PovelikinRostislav** [comment] 2017-08-14 11:09
Windows 10 x64.
tried to find all `return 1;` and change them to `return 0;` into 5 files.
Pattern for statement: `return 1(.)$` (cause Atom also have problems with `$` and `^`)
Pattern fo files **\*.h

All files were found, after `Replace all` command only in the first file changes were applied. And also it took minutes!!!

**Comment by lee-dohm** [comment] 2017-08-14 16:00
@PovelikinRostislav Please open a new issue. Because your issue is find-in-project, it isn't related to this issue.

**Comment by PovelikinRostislav** [comment] 2017-08-14 16:14
@lee-dohm I think that it's connected with find-and-replace
Please re-read my issue and told me again if I'm not right because I've told that Atom finds regexp that I want to replace but didn't replace it and says that 'nothing to replace'. If I turned off regexp within find-and-replace - it replaces fine

**Comment by lee-dohm** [comment] 2017-08-14 16:15
@PovelikinRostislav I read your issue and 1) it has nothing to do with lookarounds and 2) it is about project find which uses a different set of code with different limitations and capabilities. Please open a new issue.

**Comment by PovelikinRostislav** [comment] 2017-08-14 16:18
@lee-dohm Okey, I'm sorry, I'll do that 
I didn't want to offend or annoy anyone - I missed the main issue topic because of large amount of browser tabs opened
Sorry!

**Comment by 50Wliu** [comment] 2017-08-17 01:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #299. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-17 01:19 UTC
