### ISSUE TITLE
Regex search working for "find in file" but not for "find in project"

### ISSUE THREAD

**Issue by adamreisnz** [atom/find-and-replace#918] opened 2017-06-30 05:13 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Searching for a particular (complex multi-line) regex works on within a file, but doesn't find results when searching in project files.

### Steps to Reproduce

1. Create a file with the following code:

```js
    this.onSave({$event: {model: this.model}})
      .then(() => {
        this.form.$setPristine();
        this.card.close();
      })
      .catch(error => {
        if (error.name === 'ValidationError') {
          error.setFieldsValidity(this.form);
        }
      })
      .finally(() => this.isSaving = false);
```

2. Open find dialog and enter the following regex:

```
\.catch\(error\s\=\>\s{\n\s+if\s\(error\.name\s\=\=\=\s\'ValidationError\'\)\s{\n\s+error\.setFieldsValidity\(this\.form\);\n\s+}\n\s+}\)\n\s+
```

3. Confirm that it finds and matches code:

![image](https://user-images.githubusercontent.com/490562/27721818-4d3ee43c-5db7-11e7-8188-79f11127cdf2.png)

4. Open find in files dialog with the same regex and perform a search:

![image](https://user-images.githubusercontent.com/490562/27721826-5a011c8a-5db7-11e7-8dbb-18e335444e23.png)

**Expected behavior:** [What you expect to happen]
Since the regex matches actual code and works for find in file, it is expected that find in files will locate the file(s) with the code.

**Actual behavior:** [What actually happens]
Find in files doesn't find anything.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom    : 1.19.0-dev-0cd482c
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.6.2

**Comment by maxbrunsfeld** [comment] 2017-06-30 23:14
I think this is a duplicate of https://github.com/atom/find-and-replace/issues/398. Please subscribe there for updates. I do think we'll eventually implement this, maybe by switching our project search to use an external tool like The Silver Searcher or Ripgrep.

**Closed by maxbrunsfeld** 2017-06-30 23:14 UTC

**Comment by adamreisnz** [comment] 2017-06-30 23:59
I disagree, this is not a duplicate of that issue. 

Multiline find/replace works fine for find in buffer when using regex and `\n` characters, but the problem is that the same find/replace operation does *not* work for find in file. I would have imagined they both use a similar if not the same algorithm/engine.

**Comment by maxbrunsfeld** [comment] 2017-07-01 00:06
Yeah, they use completely separate systems out of necessity (they are doing very different jobs). Multiline patterns are completely unsupported for project search.

**Comment by maxbrunsfeld** [comment] 2017-07-01 00:06
I updated that issue's title to make it more clear that it's about project search.

**Comment by adamreisnz** [comment] 2017-07-01 02:44
Is there any idea of a timeline on that issue? It's been closed for feedback and the last comment was more than 15 months ago.

**Comment by shikkaba** [comment] 2017-09-06 05:30
Any updates on this? This would be a really huge feature.

**Comment by penx** [comment] 2018-03-06 15:57
> We will comment here as updates occur
[4 Mar 2016](https://github.com/atom/find-and-replace/issues/398#issuecomment-192323947)

lol happy 2nd birthday

**Comment by Daijobou** [comment] 2018-03-12 12:24
Here another not working single line regex variant. This working in file, but not for find in project:

`parameters\(array[^\(]`

I search for "parameters(array" but not for "parameters(array(".

**Comment by rogargon** [comment] 2019-10-03 12:51
If someone this feature, it is implemented in IntelliJ IDEA and other JetBrains products

**Comment by flisowski** [comment] 2020-02-10 12:59
> I think this is a duplicate of #398. Please subscribe there for updates. I do think we'll eventually implement this, maybe by switching our project search to use an external tool like The Silver Searcher.

The main issue has been locked. Is there anything happening with that? Very annoying.

**Comment by adamreisnz** [comment] 2020-02-10 17:08
There's not much happening with Atom in general I find. Most bugs that I
raised patiently over the years, have all recently been auto closed due to
lack of activity (20 or so in the last few weeks). They are still open and
present in Atom though.

This is one of the reasons I made the decision to move to VS Code. After an
initial adjustment period, I haven't looked back. Fewer bugs, better dev
team response to issues, much much faster especially for multi cursor
editing, etc. A shame though, because I really liked Atom.

**Comment by briancullinan** [comment] 2020-02-12 15:26
Oh, this is so frustrating. I've never used an editor where file search and project/folder search act differently. This might be enough to make me switch back to Visual Studio Code, which is also a horrible editor because of lack of control over code caching (ctags in atom).
