### ISSUE TITLE
empty results after "add project folder" with projects that have the same name

### ISSUE THREAD

**Issue by jokeyrhyme** [atom/find-and-replace#409] opened 2015-06-11 05:45 UTC
Steps to reproduce:
1. using a file manager, etc, duplicate a project folder somewhere, so both copies have the same name
2. in Atom, "open" / "add project" one of the copies
3. right-click either on the project, or on a folder within the project
4. choose "Search in Directory"
5. search for a term that is known to exist
6. **observe that results are found as expected**
7. use "Add Project Folder" to add the other copy
8. repeat the the same search, from either project, either root or sub folder within either project
9. **observe that whilst work seems to be performed, the results are empty (unexpectedly)**
10. use "Remove Project Folder" to remove one of the copies
11. repeat the same search
12. **observe that results are found again as expected**

"Find in Buffer" seems to work regardless of duplicate projects.

I noticed this whilst trying to work on both of the following projects in the same Atom window:
- https://github.com/blinkmobile/appcache-fetcher.js
- https://github.com/jokeyrhyme/appcache-fetcher.js

**Comment by maxbrunsfeld** [comment] 2015-06-16 22:28
Possibly a duplicate of https://github.com/atom/atom/issues/6134. Not sure though.

**Comment by maxbrunsfeld** [comment] 2015-06-16 22:29
@jokeyrhyme what platform and version of Atom are you using?

**Comment by jokeyrhyme** [comment] 2015-06-16 22:45
@maxbrunsfeld: Atom 0.209, OSX 10.10.4 (public beta)
I just reproduced it again.
1. `git clone` my repositories into 2 different parent folder
2. open on in Atom, search for "complexity", see results
3. add the second project to Atom, search for "complexity", wheel spins but 0 results
4. remove one from Atom, search for "complexity", see results

**Comment by maxbrunsfeld** [comment] 2015-06-16 22:51
Thanks for the exact steps @jokeyrhyme. I still can't reproduce this. At step 2, I see one result for `complexity`. At step 3, I see 2 results for `complexity`.

Are you saying the wheel never stops spinning?

**Comment by jokeyrhyme** [comment] 2015-06-16 22:59
@maxbrunsfeld: 
The wheel would stop spinning, but it would say "0 results".

Huh, just renamed both projects directories removing the ".js" on the end (so no dots). Now it works!

**Comment by jokeyrhyme** [comment] 2015-06-16 23:01
I have these cloned at:
- ~/Projects/github/appcache-fetcher.js
- ~/Projects/github/blinkmobile/appcache-fetcher.js

With the ".js", 0 results, without the ".js" I get results.
But I if I only have 1 open, then I always get results regardless of ".js".

**Comment by maxbrunsfeld** [comment] 2015-06-16 23:25
@jokeyrhyme I think this is a duplicate of atom/atom#6134. Could you subscribe to that issue for updates?

**Closed by maxbrunsfeld** 2015-06-16 23:25 UTC
Labels: needs-reproduction
