### ISSUE TITLE
"Only In Selection" mode won't update upon selection changes

### ISSUE THREAD

**Issue by LouisTakePILLz** [atom/find-and-replace#357] opened 2015-03-04 23:44 UTC
It seems like changing the selection after bringing up the `find-and-replace` pane using the *Only In Selection* mode won't update the search region, and thus will fail to mach anything upon using the *Find* function.

The only way to force updating the search region, as a workaround to this defect, is to change the search query, as shown below:

![atom-fnr selection bug](https://cloud.githubusercontent.com/assets/920910/6496095/be80cf1e-c29d-11e4-931b-7ddfc7ad5e03.gif)

**P.S.**: the Regex mode has nothing to do with the issue.

Possibly related issue: #298

**Comment by 50Wliu** [comment] 2015-03-05 00:51
Why don't you think this is a duplicate of #298?
Seems like the same issue to me.

**Comment by LouisTakePILLz** [comment] 2015-03-05 01:12
@50Wliu They're actually *quite* similar (not to say identical); however, my bug report originally involved other details, which I then edited out as I had realized they weren't relevant to this particular issue.

On another note, I believe that your explanation of the issue is a bit on the verbose side and doesn't indicate the issue quite clearly as I would have liked, but that's just me.

**Comment by 50Wliu** [comment] 2015-03-05 01:36
Yeah yours is a lot shorter yet describes it just as well :smile:.

**Comment by benogle** [comment] 2015-07-30 19:19
Closing as a dupe of #298. The author of the fix can still view this issue, but we'd like to keep the issues pretty atomic when possible.

**Closed by benogle** 2015-07-30 19:19 UTC
