### ISSUE TITLE
When window is made smaller, find & replace panel layout gets broken

### ISSUE THREAD

**Issue by adambuczynski** [atom/find-and-replace#734] opened 2016-05-27 19:48 UTC
After making my window larger, then smaller again, this is what happens to the find & replace panel:

![image](https://cloud.githubusercontent.com/assets/490562/15619409/374c220a-24a8-11e6-86a9-42ee2b5817f3.png)

It stays in that layout no matter what I do, e.g. close/reopen panel, resize window. Only closing the window and reopening helps.

The find & replace in files panel has a similar issue: it doesn't shrink back with the window being resized, so it stays in its largest position, making the buttons hidden outside the window:

![image](https://cloud.githubusercontent.com/assets/490562/15619478/82237e2c-24a8-11e6-9f1c-103eb1f231c7.png)

This is with Atom 1.9.0-dev-5eb0a03 on OS X 10.11.5.

To reproduce, simply open a window, open the find & replace panel, and resize the editor window.

**Comment by adambuczynski** [comment] 2016-05-27 19:50
Possibly more wide spread problem (Atom core?), as it also affects the About window (it doesn't shrink back):

![image](https://cloud.githubusercontent.com/assets/490562/15619511/c4d260f8-24a8-11e6-968e-68cd5b9e6a25.png)

**Comment by 50Wliu** [comment] 2016-05-27 20:15
This is a duplicate of #732 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-27 20:15 UTC

**Comment by adambuczynski** [comment] 2016-05-27 20:26
Will do, but it also affects non-folder searches.
