### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by seangates** [atom/find-and-replace#891] opened 2017-05-02 21:55 UTC
[Enter steps to reproduce:]

1. Do a project search for something (CMD + Shift + F)
2. Right-click on the path
3. Select "Copy path"

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.207.3

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project/results-view.js:400

ReferenceError: path is not defined
    at ResultsView.copyPath (/app.asar/node_modules/find-and-replace/lib/project/results-view.js:400:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:07.1.0 editor:indent (input.hidden-input)
     -3:06.6.0 intentions:highlight (input.hidden-input)
  6x -3:06.5.0 editor:move-to-end-of-word (input.hidden-input)
     -3:05.4.0 core:move-right (input.hidden-input)
     -3:05.1.0 editor:newline (input.hidden-input)
     -3:04.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:03.6.0 core:save (input.hidden-input)
  8x -2:57.5.0 core:move-down (input.hidden-input)
     -2:50.6.0 core:move-right (input.hidden-input)
     -2:50.4.0 intentions:highlight (input.hidden-input)
  3x -2:50.3.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:49.4.0 core:backspace (input.hidden-input)
     -2:48.6.0 core:save (input.hidden-input)
     -1:03.0 project-find:show-in-current-directory (span.name.icon.node-icon.medium-green)
     -0:57.2.0 core:confirm (input.hidden-input)
     -0:02.6.0 find-and-replace:copy-path (span.path-name.bright)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-django 0.3.2 
atom-email-snippets 0.1.0 
atom-html-preview 0.1.22 
autocomplete-marko 2.0.0 
busy-signal 1.4.1 
color-picker 2.2.5 
django-templates 0.5.0 
file-icons 2.1.4 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.10.1 
language-marko 2.9.3 
linter 2.1.4 
linter-eslint 8.1.6 
linter-less 2.6.0 
linter-php 1.3.2 
linter-ui-default undefined 
minimap 4.27.1 
path-hyperclick 0.3.0 
project-manager 3.3.4 
remote-atom 1.3.10 
sort-lines 0.14.0 
```

**Comment by rsese** [comment] 2017-05-03 17:14
Thanks for the report!  Can you confirm if the error is reproducible and if so, do you see the error in safe mode (atom --safe)?

I tried your steps to reproduce and don't see the error on macOS 10.12.4 and Atom 1.16.0.

**Comment by Pysis868** [comment] 2017-05-08 14:37
Was having this issue for a week or so too.
Made sure Atom and all package were up-to-date.
Upon restart, after the update, `minimap-find-and-replace` had an issue loading, so I disabled and restarted again for good measure.
Enabled `find-and-replace` since it was having an issue; seemed to work fine now.
Restarted again; still seems to be working.

I'll try to watch in case the error still happens and post here if I find anymore reproducible steps.
I did have the idea this other package *might* interact.

**Comment by sbkmmi** [comment] 2017-06-19 21:42
[Enter steps to reproduce:]

1. Search in Directory
2. Right-click on search result
3. Click on Copy Path
4. See the error

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.208.3

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At ~\AppData\Local\atom\app-1.18.0\resources\app\node_modules\find-and-replace\lib\project\results-view.js:437

ReferenceError: path is not defined
    at ResultsView.copyPath (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/find-and-replace/lib/project/results-view.js:437:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:55.4.0 project-find:show-in-current-directory (span.name.icon.icon-repo)
     -1:49.1.0 core:backspace (input.hidden-input)
     -1:47.1.0 core:confirm (input.hidden-input)
     -1:38.4.0 find-and-replace:copy-path (span.path-name.bright)
     -1:19 settings-view:uninstall-packages (div.results-view.focusable-panel)
     -0:45.6.0 core:backspace (input.hidden-input)
     -0:12.8.0 find-and-replace:copy-path (div.path-details.list-item)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
apex-ui 0.2.1 
language-salesforce 0.6.0 
minimap-find-and-replace 4.5.2 
qolor 0.4.2 
```

**Comment by 50Wliu** [comment] 2017-06-20 16:57
Fix is at #914.

**Comment by eliya111** [comment] 2017-07-11 12:16
Hi,
Still have this issue - version 1.18.0
error:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.208.3


### Stack Trace

Uncaught ReferenceError: path is not defined

```
At C:\Users\local\AppData\Local\atom\app-1.18.0\resources\app\node_modules\find-and-replace\lib\project\results-view.js:437

ReferenceError: path is not defined
    at ResultsView.copyPath (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/find-and-replace/lib/project/results-view.js:437:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  4x -4:54.2.0 find-and-replace:copy-path (span.path-name.bright)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
```

**Comment by 50Wliu** [comment] 2017-07-11 14:54
Oops, this has already been fixed but I forgot to close the issue.  Should be out in Atom 1.20.0 when it's released.

**Closed by 50Wliu** 2017-07-11 14:54 UTC
Labels: uncaught-exception

**Comment by jreynojustin** [comment] 2017-07-21 16:56
I am also still having the issue in version 1.18.0

**Comment by mhabsaoui** [comment] 2017-09-20 10:10
Still happening :/

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.208.3


### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /usr/share/atom/resources/app/node_modules/find-and-replace/lib/project/results-view.js:437

ReferenceError: path is not defined
    at ResultsView.copyPath (/usr/share/atom/resources/app/node_modules/find-and-replace/lib/project/results-view.js:437:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -6:26.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -6:20.4.0 core:close (div.panels-item)
     -6:08.3.0 project-find:show-in-current-directory (span.name.icon.icon-repo)
     -6:06.4.0 core:paste (input.hidden-input)
     -5:46.3.0 find-and-replace:copy-path (span.path-name.bright)
     -5:17.2.0 core:close (input.hidden-input)
     -5:14.2.0 find-and-replace:show (div.results-view.focusable-panel)
  3x -3:49.5.0 core:undo (input.hidden-input)
     -3:37.4.0 core:paste (input.hidden-input)
     -3:36.7.0 core:confirm (input.hidden-input)
     -2:44.4.0 core:copy (div.line)
     -1:57.3.0 find-and-replace:copy-path (span.path-name.bright)
     -0:10 project-find:show-in-current-directory (span.name.icon.icon-repo)
     -0:05.5.0 core:confirm (input.hidden-input)
     -0:02.1.0 find-and-replace:copy-path (span.path-name.bright)
```

### Non-Core Packages

```
file-icons 2.1.12 
```

`

**Comment by 50Wliu** [comment] 2017-09-20 10:18
@mhabsaoui Please read my comment; this has been fixed in Atom 1.20, while you are running Atom 1.18.

**Comment by mhabsaoui** [comment] 2017-09-20 11:01
Ok. That's All right.

**Comment by mhabsaoui** [comment] 2017-09-20 11:01
Ok. That's All right. Thanks
