### ISSUE TITLE
Find & replace in files gets stuck and unable to save files when they are open in a tab

### ISSUE THREAD

**Issue by adambuczynski** [atom/find-and-replace#735] opened 2016-05-27 19:54 UTC
I find that since a couple of the latest Atom builds find & replace is unable to process all files anymore. It gets stuck somewhere in the middle like this:

![image](https://cloud.githubusercontent.com/assets/490562/15619593/5205e97c-24a9-11e6-88f9-806e07e819a8.png)

The progress bar stops moving and it doesn't complete the operation.

This is with Atom 1.9.0-dev-5eb0a03 on OS X 10.11.5.

To reproduce, do any find & replace which affects several files.

**Comment by adambuczynski** [comment] 2016-05-28 00:58
This is constantly reproducible on both my computers (both OS X 10.11.5), for any find & replace in files:

![image](https://cloud.githubusercontent.com/assets/490562/15624126/d11e0b84-24d3-11e6-85af-fd3139e026b8.png)

This computer has a slightly older Atom 1.9.0-dev-7253514.

**Comment by adambuczynski** [comment] 2016-05-28 01:05
To reproduce:

```
mkdir test
cd test
echo "test" >> test1.js
echo "test" >> test2.js
echo "test" >> test3.js
echo "test" >> test4.js
atom .
```

1. Open two of the test files in a tab
2. Open find & replace
3. Replace `test` with `abc`
4. Press find, and then replace all
5. Find & replace hangs.

**Comment by adambuczynski** [comment] 2016-06-06 21:05
Still an issue in Atom 1.10.0-dev-672cf6d.

It's making replacements in files pretty unworkable if you have to close all open tabs that might have the search term in them first.

**Comment by adambuczynski** [comment] 2016-06-12 19:08
@50Wliu have you checked with my reproduction steps? I am able to reproduce this consistently, on both my computers (OS X).

**Comment by 50Wliu** [comment] 2016-06-12 20:10
I can't reproduce this on Windows 10 x64, Atom 1.9.0-dev-3b9b28d.

**Comment by adambuczynski** [comment] 2016-06-12 20:54
@50Wliu is there anyone on the dev team with OS X 10.11.5 that can try to reproduce? It might be a mac only issue.

**Comment by 50Wliu** [comment] 2016-06-12 21:33
@atom/feedback

**Comment by r-murphy** [comment] 2016-06-21 04:53
I have been bit badly by this bug a few times lately. I did a project wide find-replace and some files didn't get updated, which resulted in some hard to find bugs.

OSX 10.11.5
Atom 1.8.0

**Comment by simurai** [comment] 2016-06-21 05:39
Followed these repro steps https://github.com/atom/find-and-replace/issues/735#issuecomment-222281833 with `1.10.0-dev-56a9894` on `OS X 10.11.5`. But can't reproduce either:

![find](https://cloud.githubusercontent.com/assets/378023/16218986/9a5ad6de-37bd-11e6-8c3b-4ba99fba3603.gif)

@adambuczynski Does it also happen with `atom . --safe`?

**Comment by adambuczynski** [comment] 2016-06-21 05:46
@simurai on what OS X version are you? I'll check if it happens in safe mode for you, but I didn't install any new/odd packages lately so not sure what could impact it. I did upgrade the OS from 10.10.x to 10.11.x, so maybe that influenced it.

**Comment by adambuczynski** [comment] 2016-06-21 05:51
@simurai Have tested with `atom --safe` and it doesn't happen. Is there a strategy you recommend for me to pinpoint if/what package might be the culprit other than enabling/disabling them one by one?

**Comment by thomasjo** [comment] 2016-06-21 05:53
@adambuczynski [package-cop](https://atom.io/packages/package-cop) might be able to help you track down the culprit 👮

**Comment by adambuczynski** [comment] 2016-06-21 06:03
@thomasjo brilliant package, the culprit has been identified:

![image](https://cloud.githubusercontent.com/assets/490562/16219437/6e4e4266-37da-11e6-9c9e-5b5991034c7d.png)

I will head over there and file an issue there. Thanks everyone for the help so far. I will make sure to test with `atom --safe` first next time.

**Comment by adambuczynski** [comment] 2016-06-21 06:09
By the way, even though linter-jscs is the culprit, i think maybe find & replace package needs to be a bit more robust about how it handles failures. It seems to me the problem is that linter doesn't allow find & replace to save a particular file (which is open), and that in result causes find & replace to hang. Find & replace should probably report the error, but keep going and replace the rest of the files.

**Comment by r-murphy** [comment] 2016-06-21 06:37
Thanks for the help and `--safe` tip. My culprit was tidy-markdown, and probably due to open issue https://github.com/slang800/atom-tidy-markdown/issues/22. None of the files being updated were event markdown.

I also think it would be good for find-and-replace to move on after a package experiences an issue. Here's my stack in case it helps with that.

```
TypeError: Cannot read property 'getGrammar' of undefined
    at TidyMarkdown.run (index.coffee:19)
    at index.coffee:11
    at TextBuffer.module.exports.TextBuffer.transact (/Apps/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buf…:828)
    at index.coffee:11
    at Function.module.exports.Emitter.simpleDispatch (/Apps/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25)
    at Emitter.module.exports.Emitter.emit (/Apps/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Apps/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buf…:1091)
    at TextBuffer.module.exports.TextBuffer.save (/Apps/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buf…:1083)
    at TextBuffer.module.exports.TextBuffer.replace (/Apps/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buf…:978)
    at /Apps/Atom.app/Contents/Resources/app.asar/src/workspace.js:1073
    at Workspace.module.exports.Workspace.replace (/Apps/Atom.app/Contents/Resources/app.asar/src/workspace.js:1032)
    at ResultsModel.module.exports.ResultsModel.replace (/Apps/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/pro…:215)
    at /Apps/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/pro…:529
```

**Comment by adambuczynski** [comment] 2016-07-08 19:05
@50Wliu now that we have found that the issue was with `linter-jscs` (I've since switched to ESLint), we can close this. But before we do, what do you think about what I said above?

> Even though linter-jscs is the culprit, i think maybe find & replace package needs to be a bit more robust about how it handles failures. It seems to me the problem is that linter doesn't allow find & replace to save a particular file (which is open), and that in result causes find & replace to hang. Find & replace should probably report the error, but keep going and replace the rest of the files.

Should we create a new issue to cover that enhancement?

**Comment by mnquintana** [comment] 2016-07-08 19:26
@adambuczynski That sounds good – would you mind making a new issue for that? 😄 

Closing this out now

**Closed by mnquintana** 2016-07-08 19:26 UTC
Labels: needs-reproduction
