### ISSUE TITLE
"Close Project Find Panel After Search" option producing strange behaviour

### ISSUE THREAD

**Issue by mamartins** [atom/find-and-replace#638] opened 2016-01-07 15:38 UTC
Hi guys,

on OSX, and with atom 1.3.2 if I have the "Close Project Find Panel After Search" toggle turned on, for every char I try to insert in the "Replace in project" input make the find panel close. I also cannot use the "Replace All" when the same toggle is on because the button is grayed out.

**Comment by amytruong** [comment] 2016-01-08 02:10
I was able to reproduce this. Def a bug. 
Thanks @mamartins!

**Comment by mamartins** [comment] 2016-01-08 10:26
you're welcome :)

**Comment by Ben3eeE** [comment] 2016-08-31 06:50
https://github.com/atom/find-and-replace/issues/612

**Comment by 50Wliu** [comment] 2016-08-31 20:22
Closing as a duplicate of #612 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-31 20:22 UTC
Labels: bug
