### ISSUE TITLE
Find in project not working

### ISSUE THREAD

**Issue by zzzbra** [atom/find-and-replace#543] opened 2015-10-02 16:46 UTC
OS: OSX 10.11 El Capitan
Atom ver.: 1.0.19

Not sure what else to say except that searching across the project returns "No results found for 'xxxxxxx'" every time. I think this may have only become an issue after installing Vim mode, but I'm not certain of that. Some of the settings from that package may have overwritten the config for Find and Replace.

**Comment by benogle** [comment] 2015-10-02 17:38
Can you try starting atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If still broken, can you 

1. paste in your config file
1. point us to a public repository highlighting the issue
1. indicate a specific search string + options that doesnt work

**Comment by hdavidzhu** [comment] 2015-10-06 05:57
I'm also having this issue:

![not_found](https://cloud.githubusercontent.com/assets/3756871/10301106/232a45f2-6bcd-11e5-8ff2-d37dea0653c7.png)

Above is the search in safe mode. Here is my `config.cson` file:
```
"*":
  editor:
    invisibles: {}
    fontFamily: "Hack"
    fontSize: 13
  core:
    themes: [
      "atom-material-ui"
      "monokai"
    ]
    audioBeep: false
  welcome:
    showOnStartup: false
  "atom-material-ui":
    depth: true
  react: {}
  "exception-reporting":
    userId: "a69c6dde-173a-f526-c0b7-1c13772f17eb"
  emmet: {}
  "markdown-preview":
    useGitHubStyle: true
  "auto-update-packages": {}
  term2:
    fontFamily: "Hack"
  "find-and-replace": {}
```

Interestingly, when I go and click `OPEN CONFIG FOLDER` I can search in the config project...

**Comment by gaelenh** [comment] 2015-11-11 21:20
I have this issue too.  Specifically, the issue arises when I launch atom to a subdirectory of a git repository.  Here is a quick way to reproduce:

```
git init no-results-test
mkdir -p no-results-test/subdir/
printf "find this text here" > no-results-test/subdir/test.txt
printf '/*\n!/subdir\n' > no-results-test/.gitignore
```

Launch ```atom --safe no-results-test``` and do a find all for 'text'.

![screen shot 2015-11-11 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/325937/11103208/1174c416-888f-11e5-86d4-4093acc022cf.png)

Launch ```atom --safe no-results-text/subdir``` and do a find all for 'text'.

![screen shot 2015-11-11 at 4 10 26 pm](https://cloud.githubusercontent.com/assets/325937/11103221/2024c9e8-888f-11e5-99e4-3016ec0c21d5.png)

Disabling "Exclude VCS Ignored Paths" fixes the issue, so the bug seems to be in how the **options.excludeVcsIgnores** is handled by the searcher, not the find-and-replace package.

**Comment by JulienBrks** [comment] 2016-04-14 08:59
OS: OSX 10.11.4 El Capitan
Atom ver.: 1.7.0

I have the same issue and it works in safe mode.

**Comment by JulienBrks** [comment] 2016-04-14 09:22
My issue Solved!  My issue is caused by the atom package "default-encoding", see the issue in https://github.com/russlescai/atom-default-encoding/issues/3 .

**Comment by ruakura** [comment] 2016-08-04 20:59
I'm seeing this issue as well, due to looking at a subfolder of a git repo. Disabling "Exclude VCS Ignored Paths" does indeed make search work again (including the essential ability to search in the current file).

As a workaround it's of limited use though, as whole-project searches now take forever, searching in ignored folders (such as node_modules).

Would really like to see this fixed!

**Comment by asmaloney** [comment] 2016-08-13 21:02
@ruakura Thank you. Disabling *Exclude VCS Ignored Paths* solved it for me too.  A super-annoying bug.

I think what's happening in my case is that the path to my Go project **~/dev/go/src/github.com/asmaloney/foo** is being ignored because it thinks they are VCS files.  (The project is not yet under version control.)

If I use another Go project outside that path the search works properly.

**Comment by barbalex** [comment] 2016-08-25 06:53
Same problem here on windows 10, Atom 1.9.9.

Disabling Exclude VCS Ignored Paths solves it too.

Have not changed .gitignore in 27 days.

Oh, that last change was the reason:

    npm-debug.log*

seems to cause this behaviour in my case!

**Comment by barbalex** [comment] 2016-08-25 14:24
npm-debug*

works to keep the debug logs out

**Comment by janwijbrand** [comment] 2017-02-28 08:55
This bug seems present still (Atom 1.14.3).

**Comment by bfintal** [comment] 2017-03-01 05:01
Happening to me also solved by disabling Exclude VCS Ignored Paths

**Comment by tpazitny** [comment] 2017-03-02 15:32
This is happening to me as well and was not solved by disabling Exclude VCS Ignored Paths. I have atom both on my macbook and my windows box and this is only happening on my windows box.

**Comment by micampbell** [comment] 2017-03-06 22:24
I haven't seen "find" work on Windows or Linux. I have unchecked Exclude VCS Ignored Paths, but the problem persists.

**Comment by tpazitny** [comment] 2017-03-22 01:48
@micampbell a head's up - I finally caved and opened up a separate issue for my continued problem, but then I figured it out same day. Maybe this will help you.  https://github.com/atom/find-and-replace/issues/877

**Comment by daniel-z** [comment] 2017-04-12 21:51
This happened to me and is aso fixed by disabling Exclude VCS Ignored Paths.

**Comment by micampbell** [comment] 2017-04-12 22:14
Yes, it is fixed now. I believe this can be closed.

**Comment by daniel-z** [comment] 2017-04-12 22:41
@micampbell in which version is this solved? I have Atom 1.15.0

**Comment by janwijbrand** [comment] 2017-04-14 06:47
@micampbell I don't think this is fixed. Same behaviour still in Atom 1.16.0 on macOS.

It would be nice if we can confirm whether this is regarded as a bug or "just" a side-effect from a feature that really does what it needs to do. I like having  Exclude VCS Ignored Paths enabled in general.

**Comment by micampbell** [comment] 2017-04-14 15:54
sorry for stating it should be closed. It is working for me now, but I don't know why. Please disregard me (at least in this thread).

**Comment by peterplus1** [comment] 2017-05-09 17:59
It has to do with paths and files ignored by .gitignore , Atom doesn't search those. If you committed files to Git then Git will start tracking those files, but Atom still ignores them. You should check your .gitignore to see if there are files and folders that would've been ignored if you had created them now. If so, remove the ignore or include them with an exclamation mark. Disabling "Exclude VCS Ignored Paths" is not a good solution in my opinion, as it decreases the search and indexing performance of Atom.

.gitignore example:
> /*
> !themes

This ignores everything except the themes folder, also for Atom.

**Comment by lipeng1667** [comment] 2017-05-16 02:22
Looks like if your file's encoding is **NOT** UTF-8, this 'find in project' will NEVER be worked

**Comment by reduardo7** [comment] 2017-11-17 14:44
It happens on Ubuntu too.

**Comment by JetUni** [comment] 2017-12-19 17:22
This is still happening!!! Please fix it! I've tried running it in safe mode, I've tried running `atom .atom-backup` to erase all my settings and configuration, I've tried disabling "Exclude VCS Ignored Paths", I've tried checking my `.gitignore` to make sure nothing is impeding the search and NOTHING is working! This has been an issue for over 2 years! What more do you need to get this fixed? I'm sure that there are people here that are more than willing to give more input to get this issue resolved.

**Comment by reduardo7** [comment] 2017-12-19 18:50
@JetUni I fix it with:
> This happened to me and is aso fixed by disabling Exclude VCS Ignored Paths.

https://github.com/atom/find-and-replace/issues/543#issuecomment-293718029

**Comment by JetUni** [comment] 2017-12-19 19:19
@reduardo7 I already tried that and mentioned it in my comment. Didn't do anything for me.

**Comment by tpazitny** [comment] 2017-12-19 19:21
@JetUni did you check out the issue linked in my comment from a few months back? It might help you.

https://github.com/atom/find-and-replace/issues/877

**Comment by simanwhite** [comment] 2018-01-10 05:32
Find result will appears every time when I change file encoding in Core-setting. But gives 'no results' again when I start a new search.

**Comment by asmaloney** [comment] 2018-04-14 20:38
This is still a bug on macOS.

Disabling _Exclude VCS Ignored Paths_ still solves it but is annoying. (Some Atom update reset all my prefs and it took me a long time to figure out why searching wasn't working anymore.)

**Comment by ChrisTalman** [comment] 2018-05-05 16:04
Just experienced this problem on Windows 10.

The `Exclude VCS Ignored Paths` solution does not seem to work for me.

Any word on a fix for this?

**Comment by kuroda** [comment] 2018-05-07 02:52
I think I found a possible solution for this issue.

Summary: Detect a malfunctioning package and uninstall it.

----

I supposed that one of 17 packages installed on my Atom caused this issue. So, I tried to detect which one does.

1. I started Atom from terminal with `atom --safe` command so that it does not load community packages and my init script.
1. I confirmed that the "Find in project" works well.
1. I restarted Atom without `--safe` option.
1. I divided 17 packages into two groups to narrow down the investigation range.
1. I disabled all packages of the first group.
1. After restarting Atom, I checked if the "Find in project" works well.
1. I did the same thing for the second group.
1. I found the second group includes one or more _bad_ packages.
1. I continued investigation with similar procedure and hunted down a package finally.
1. I uninstalled it, restarted Atom, and confirmed that the "Find in project" works well.

In my case, [default-encoding](https://atom.io/packages/default-encoding) is the origin of problem.

In retrospect, after updating Atom recently, a warning message like "Cannot load the system dictionary for ..." started appearing. This might have been a symptom of my problem.

I hope my experience helps someone.

**Closed** 2018-09-25 19:42 UTC
Labels: more-information-needed

**Comment by HebaruSan** [comment] 2021-11-06 19:25
I'm seeing something similar on Ubuntu 21.10. After years of using Atom's find-in-files without problems, Atom 1.58.0 suddenly says it can't find "Add to Favourites" anywhere in [the Pitivi source code](https://gitlab.gnome.org/GNOME/pitivi), see safe mode screenshot:

![image](https://user-images.githubusercontent.com/1559108/140621296-c71f4d8d-bdd7-4779-a198-9244dff39f95.png)

But it finds them if I explicitly add `*.po` to the file pattern input (i.e., if I already know what I'm looking for rather than my editor helping me with that):

![image](https://user-images.githubusercontent.com/1559108/140621371-d9ae6e69-f75b-4849-9e51-369574292456.png)

Maybe Atom thinks `.po` files are binaries? If so, how can I tell it otherwise?
