### ISSUE TITLE
Find and replace regex not working despite correct preview

### ISSUE THREAD

**Issue by willdady** [atom/find-and-replace#788] opened 2016-10-04 23:24 UTC
I have the following regex

`^\}\);`

which I want to replace with

`}`

The search preview is correct but when I press _Replace All_ there is no effect. Nothing changes. I'm trying to replace this across about 80 files. It seems to work fine when doing it file-by-file. Atom 1.10.0 on OSX.

**Comment by DanielSWolf** [comment] 2016-11-08 15:54
I'm having the exact same problem. I'm trying to replace

`^(\s*\*)\s*<p>\s*$`

with 

`$1`.

The preview works; a dialog asks me whether I'm sure; and nothing happens.

**Comment by cconover** [comment] 2016-11-13 06:41
I'm having this problem as well.

**Comment by heruan** [comment] 2016-12-07 09:20
Same here, the preview is correct:

![screen shot 2016-12-07 at 10 17 25](https://cloud.githubusercontent.com/assets/851745/20961742/abfcc7f2-bc66-11e6-8449-9c842dac4f9a.png)

but then nothing happens:

![screen shot 2016-12-07 at 10 18 27](https://cloud.githubusercontent.com/assets/851745/20961751/b84616c6-bc66-11e6-902c-4a8b1a7dfc1a.png)

**Comment by 50Wliu** [comment] 2016-12-07 22:52
This is a duplicate of #622 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-12-07 22:52 UTC
