### ISSUE TITLE
Sort results by path (Project Find Results)

### ISSUE THREAD

**Issue by collinstocks** [atom/find-and-replace#641] opened 2016-01-11 19:15 UTC
This is a feature request.

When doing a global search in my project, the result files seem to appear in a random order:
![punctuated](https://cloud.githubusercontent.com/assets/928827/12243541/360da7d0-b86d-11e5-9021-6038a956115f.png)

Several results are listed from `common/`, then from `utils/`, then `bees/`, then `crawler2/`, then `common/` again. It would be really helpful to sort these results by path so that on the occasion that results from one directory don't matter, I can just skip over those results and be confident that there are no results from other directories punctuating the results from the directory I don't care about.

**Comment by benogle** [comment] 2016-01-15 18:54
They should be sorted. See https://github.com/atom/find-and-replace/pull/485. This definitely could be a regression.

What version of atom are you on?

**Comment by collinstocks** [comment] 2016-01-18 20:13
I'm on 1.0.5.

**Comment by collinstocks** [comment] 2016-01-18 20:14
I'm on find-and-replace 0.176.0.

**Comment by 50Wliu** [comment] 2016-01-19 00:33
@collinstocks Please update to Atom 1.4.0, and then try again.

**Comment by collinstocks** [comment] 2016-01-19 17:43
Thanks, it appears that fixed it. Is there a ppa or something that will always have the most recent updates of Atom? I'm not used to manually updating all my packages.

**Comment by Ben3eeE** [comment] 2016-12-15 15:46
Looks like this was solved by updating Atom, closing.

**Closed by Ben3eeE** 2016-12-15 15:46 UTC
Labels: more-information-needed
