### ISSUE TITLE
Atom closes "Find in Project" panel if "Replace in project" text field is changed

### ISSUE THREAD

**Issue by alexesprit** [atom/find-and-replace#867] opened 2017-03-05 13:37 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom

### Description

Atom closes "Find in Project" panel if "Replace in project" text field is changed. This happens only if "Close Project Find Panel After Search" option is enabled.

### Steps to Reproduce

1. Go to "find-and-replace" package settings.
2. Enable "Close Project Find Panel After Search" option.
3. Open "Find in Project" panel (I use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> combination).
4. Enter some text in "Replace in project" text field.

**Expected behavior:** The panel is visible while entering text.

**Actual behavior:** The panel is closed if I start typing.

**Reproduces how often:** 100%.

### Versions

Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by 50Wliu** [comment] 2017-03-06 15:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #612. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-03-06 15:49 UTC
