### ISSUE TITLE
Replace All breaks when replacing php arrow accessors with PHP language enabled

### ISSUE THREAD

**Issue by Torniojaws** [atom/find-and-replace#1083] opened 2019-05-21 11:09 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using `Replace All` on a php file with php language package enabled, the replace breaks on arrow accessors (`$obj->property`) and stops replacing after the first item.

### Steps to Reproduce

1. Create a new file
2. Make its contents:
```
<?php
example->value;
another->value;
```
3. Change the syntax from "Plain Text" to "PHP" in the bottom taskbar
4. Select the last two rows (begins with "example" and "another")
5. Press Ctrl/Command+F to open the search bar
5. In the "Find" bar, enable "Regex" and "Only in selection"
6. In the Search field, write: `\-\>`
6. In the Replace field, write `['`
7. Press "Find All"
8. Press "Replace All"

**Expected behavior:** [What you expect to happen]

The file contents change from:
```
<?php
example->value;
another->value;
```
To this:
```
<?php
example['value;
another['value;
```

**Actual behavior:** [What actually happens]

The contents become:
```
<?php
example->value;
another['value;
```
And the search bar says: "no results", so you cannot press "Replace" or "Replace All" again to continue replacing.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time. 100 % 

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.10
git 2.20.1

MacOS Mojave 10.14.4

**Comment by rsese** [comment] 2019-05-22 22:52
Thanks for contributing!

Though I can reproduce, this looks like a duplicate of https://github.com/atom/find-and-replace/issues/1010 so you can subscribe there for updates if you'd like.  If I'm misunderstanding, please let me know :v:

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-05-22 22:52 UTC

**Comment by Torniojaws** [comment] 2019-05-23 08:37
Ah yes, it appears to be the same. It seems if you search from the main atom project, it doesn't show the subprojects like `find-and-replace` :) Since I searched for the exact term that ticket has in its title (`Replace All`).

**Comment by rsese** [comment] 2019-05-23 18:43
Yeah a couple of search quirks there but thanks for searching for previous reports :bow:

If you haven't come across it already, you can search across repositories under the Atom organization from the search bar on any page with something like this for example `org:atom is:issue within selection`:

https://github.com/search?q=org%3Aatom+is%3Aissue+within+selection

You also need to choose the dropdown option to search `All GitHub`.

Or if you search from the [Atom organization page](https://github.com/atom), the search bar will scope your search to the organization by default.
