### ISSUE TITLE
Cannot search and replace multiple lines in project

### ISSUE THREAD

**Issue by jannisborgers** [atom/find-and-replace#425] opened 2015-07-01 12:56 UTC
For smaller, static websites, I often find myself having to replace whole regions of multiple HTML files (navs, footer sitemaps, etc.) that have the same content and I want to replace with a newer version of that content.

I tried using „Find in project“, each time pasting the region I want to search for (in this case, 3 lines), but the search results come up without hits.

Step 1: I select the lines, paste them in both the search and replace fields, and make my changes in the latter
![bildschirmfoto 2015-07-01 um 14 33 45](https://cloud.githubusercontent.com/assets/9452571/8454639/72793362-1fff-11e5-871b-a569c9a3a91d.png)

Step 2: I hit return. The string is not found.
![bildschirmfoto 2015-07-01 um 14 34 05](https://cloud.githubusercontent.com/assets/9452571/8454642/7613cabe-1fff-11e5-9744-ec8ab740361d.png)

Because I indent my HTML, the preceding tabs are not transported to the input fields correctly and are omitted. Turning RegEx on does not change the results, putting something like „*.html“ in the scope field also does nothing.

Also note that I’m unsure if this is even an issue, or I’m just using the function in a wrong way, missing something?

Mac OS X Yosemite, Atom 1.0.0, with the following community packages installed:

![bildschirmfoto 2015-07-01 um 14 41 26](https://cloud.githubusercontent.com/assets/9452571/8454625/4cbf0e62-1fff-11e5-8fe1-9200436e713e.png)

**Comment by benogle** [comment] 2015-07-01 15:47
Thanks for the report. Project find currently doesnt search across line boundaries. Closing as a dupe of https://github.com/atom/find-and-replace/issues/218

**Closed by benogle** 2015-07-01 15:47 UTC
