### ISSUE TITLE
Project wide find and replace not working in Atom 1.19.3

### ISSUE THREAD

**Issue by AustP** [atom/find-and-replace#946] opened 2017-08-23 16:04 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When trying to find and replace in project, the find and replace panel closes after 1 keystroke in the "Replace in project" textfield. It also closes after clicking the "Find All" button.

### Steps to Reproduce

1. Ctrl + Shift + F to open find and replace in project.
2. Type anything into the "Find in project" textfield
3. Type 1 character into the "Replace in project" textfield

**Expected behavior:** The character to show up in the textfield and the panel to stay open so you can type more characters.

**Actual behavior:** The panel immediately closes. If you open the panel back up, the character is still there and you can add more characters if you repeat the process of type 1, reopen panel, type 1, reopen panel, etc. However, since the panel also closes when you press the "Find All" button, you can't make any replacements. When you re-open the panel it asks you to [run a search to enable].

**Reproduces how often:** 100%

### Versions

Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

Ubuntu 16.04 LTS

### Additional Information

I just upgraded from 1.19.0 this morning. I did not have this issue in 1.19.0.

**Comment by Ben3eeE** [comment] 2017-08-23 16:15
Do you have the `Close Project Find Panel After Search` option enabled in the find-and-replace package settings?

**Comment by AustP** [comment] 2017-08-23 16:17
@Ben3eeE Yes I do.

I toggled that off and tested and the panel worked as expected.

**Comment by AustP** [comment] 2017-08-23 16:19
Also note that I downgraded back to 1.19.0 and the issue was there. So perhaps I was having the issue before and didn't notice. I also upgraded to 1.20.0-beta4 and the issue was still there.

**Comment by 50Wliu** [comment] 2017-08-23 16:25
Cannot reproduce on Atom 1.21.0-dev-a1fdf52ed.  This looks like it was fixed in find-and-replace@0.209.3, which will be released in Atom 1.20.0.

**Comment by Ben3eeE** [comment] 2017-08-23 16:36
I am unable to reproduce when trying with Atom 1.20.0-beta4.

**Comment by AustP** [comment] 2017-08-23 16:37
@50Wliu @Ben3eeE 

Yeah you're right. I didn't realize I had to run Atom beta with the `atom-beta` command rather than `atom`. It looks good to me in beta as well.

**Closed** 2017-08-23 16:40 UTC
Labels: more-information-needed
