### ISSUE TITLE
Failed to activate the find-and-replace package

### ISSUE THREAD

**Issue by fusan** [atom/find-and-replace#573] opened 2015-10-27 03:29 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.181.0

### Stack Trace

Failed to activate the find-and-replace package

```
At ENOENT: no such file or directory, lstat '/Users/fusanbook/Downloads/Atom.app'

Error: ENOENT: no such file or directory, lstat '/Users/fusanbook/Downloads/Atom.app'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
  at toRealPath (module.js:108:13)
  at tryFile (module.js:104:22)
  at tryExtensions (module.js:114:20)
  at tryPackage (module.js:92:31)
  at Function.Module._findPath (module.js:155:20)
  at Module._resolveFilename (module.js:332:25)
  at Function.Module._resolveFilename (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:4:7)
  at Object.<anonymous> (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:269:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at Package.module.exports.Package.activateNow (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:241:14)
  at /Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/fusanbook/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  2x -3:27.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:21.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:06.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:59.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:43.3.0 core:cut (atom-text-editor.editor.is-focused)
     -1:39.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:43.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:00.0 find-and-replace:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by thedaniel** [comment] 2015-10-27 14:52
Did you perhaps run Atom from your Downloads folder and then move or delete it right away? Can you reproduce this consistently?

**Comment by coldfight** [comment] 2015-11-05 15:25
Try this:
1. Disable the 'find-and-replace' package
2. Close down Atom
3. Open Atom
4. Re-enable the 'find-and-replace' package

I was getting this error too, and then I did the above steps and it started working again.

**Comment by EvanGoss** [comment] 2015-11-05 19:56
I started getting this error after I accidently pasted about 2400 lines of Apache activity log file into the 'find' field.  I don't know if it's related, but I had the regex button turned on.

Since Find and Replace stores the find and replace field contents across sessions, I can't seem to get rid of the error.  So far I've only tried disabling the find and replace package, restarting, then reenabling  the package.

My next thought is to find where the field contents are stored and clear out the bad data, if possible.

**Comment by EvanGoss** [comment] 2015-11-05 20:36
I managed to fix my problem.  On my system, I discovered that the file /users/username/.atom/storage/editor-4b1420d72589eec9ec4b95f813aaf16f6802f4de stores the contents in the "find" field under findPattern.  I simply removed the contents and now I'm back in business.

**Comment by coldfight** [comment] 2015-11-06 09:41
Hmmm.. That's interesting! Thanks for sharing your solution. Hopefully this will help others.

**Comment by chrishough** [comment] 2015-11-25 01:31
:smile_cat:  Thank you @EvanGoss  that fixed my issue too. Cheers.

**Comment by KevinMcCoy** [comment] 2015-12-11 03:58
Ditto, thanks @EvanGoss

**Comment by josephfusco** [comment] 2016-01-14 15:34
Solved my issue @EvanGoss Thanks. :+1:

**Comment by remivigan** [comment] 2016-01-23 17:17
Thanks @EvanGoss ! :+1:

**Comment by Riveascore** [comment] 2016-02-16 17:37
Thanks @EvanGoss, though this wasn't enough for me.
I needed to delete as much as I could in `/users/username/.atom/`:

- Everything in `/storage`
- All in `/compile-cache`
- Every file inside `/blob-store`

**Comment by lee-dohm** [comment] 2016-02-19 17:27
Closing this since we didn't get a response from the original author. The other issues seem to be unrelated. (Though I am glad that people are finding help :grinning:)

**Closed by lee-dohm** 2016-02-19 17:27 UTC
Labels: more-information-needed

**Comment by JeanReneRobin** [comment] 2016-02-29 09:33
@Riveascore's answer solved my issue. Thank you for sharing.
