### ISSUE TITLE
Global find and replace behavior drastically different than local w/ regex

### ISSUE THREAD

**Issue by envygeeks** [atom/find-and-replace#1017] opened 2018-04-26 13:18 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`mit\slicense$\n^$\n` regexp does not work with global find and replace

### Steps to Reproduce

1. Create a file
2. Open said file
3. Add "MIT License\n\n"

**Expected behavior:** A match
**Actual behavior:** No Match
**Reproduces how often:** 100%

### Versions

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

<img width="1280" alt="screen shot 2018-04-26 at 8 16 22 am" src="https://user-images.githubusercontent.com/99763/39308134-4c50e2aa-492a-11e8-87ea-1c02082df6da.png">
<img width="1280" alt="screen shot 2018-04-26 at 8 16 42 am" src="https://user-images.githubusercontent.com/99763/39308146-4f99c60c-492a-11e8-8640-afbd01392432.png">

**Comment by outbools** [comment] 2018-05-15 05:33
#218 
**4 years**

**Comment by thomasjo** [comment] 2018-05-15 08:45
Closing as duplicate of #218.

**Closed by thomasjo** 2018-05-15 08:45 UTC

**Comment by envygeeks** [comment] 2018-05-15 14:35
@thomasjo This isn't about `\s` this about `\n^$\n`, `\s` works regardless of scope.

**Comment by thomasjo** [comment] 2018-05-15 15:04
Perhaps I should have been more explicit in my comment above.

If you read the duplicate issue carefully, you will see that this is [by design](https://github.com/atom/find-and-replace/issues/218#issuecomment-44068863) due to how the [scandal](https://github.com/atom/scandal) library works; it splits each file into lines, and therefore only runs regex search patterns on line-by-line basis. In other words, searching across multiple lines is not supported with project-wide searches.

---
Ref: https://github.com/atom/scandal/issues/5

**Comment by envygeeks** [comment] 2018-05-16 16:17
Ah boo, I didn't know that 😭.  That explains a lot then. I've subscribed to that thread.
