### ISSUE TITLE
Ability to search in .gitIgnored files & folders

### ISSUE THREAD

**Issue by jamischarles** [atom/find-and-replace#207] opened 2014-05-13 23:53 UTC
Sometimes it's very useful to search within the node_modules folder for errors and other code.

Can there be a search option to search through node_modules folders and other ones that are commonly ignored?

**Comment by sabeerzaman** [comment] 2015-01-07 23:07
+1
I think a handy keybinding to toggle this option on and off would really give the most flexibility, where you can explicitly search for gitignored files really quick vs not.

**Comment by NathanRSmith** [comment] 2015-01-17 21:20
+1

**Comment by sylus** [comment] 2015-01-18 16:33
I have to admit I am still curious as to how this is marked as an enhancement and not a bug. It is because of this issue I can't switch my IDE from sublime to atom.

**Comment by NathanRSmith** [comment] 2015-01-18 16:40
Indeed. It is quite annoying when developing multiple packages and using 'npm link' or 'bower link' that have their own repos and I don't want them in my git status all the time. I usually end up opening textmate when I need to search these dirs.

**Comment by zwhitchcox** [comment] 2015-01-18 16:47
one solution, and please tell me if this is not adequate, would be just be to right click on the module you want and then say "search this directory"

that will bring up all the search results for that directory, excluding the ones in node_modules, .gitignore, etc.

that's what i need to do most of the time. it's very rare that i really want to search every module and every submodule and every sub-sub-module, etc.

does this make sense to everyone?

if so, how can we package this and make it more user friendly for the masses?

**Comment by NathanRSmith** [comment] 2015-01-18 16:50
That would definitely be an improvement @zwhitchcox.

**Comment by nmccready** [comment] 2015-01-18 16:53
To be consistent with the UI a check box or a (inclusion  regex)  for find all would be  nice. Check box for including hidden directories.

**Comment by Globegitter** [comment] 2015-02-10 13:20
Just ran into this now as well. It is quite unintuitive that you click 'search in directory' and your are lead to believe it should work but it does not.
Had to open my project in sublime just to get that feature to work.

The toggle is good to have as a temporary workaround, but I agree with a lot of the other people here. This should be marked as a bug and you should either just be able to search in VCS ignored Paths or at the minimum have a quick toggle in the search field.

So tl;dr; +1 on this.

**Comment by roopemerikukka** [comment] 2015-02-24 12:32
I also noticed that this doesn't follow same rules as .gitignore. In example if I have settings like this in my .gitignore file:
````
somefolder/*
!somefolder/subfolder
````
This ignores everything from somefolder except the subfolder within git but the search ignores that subfolder also.

**Comment by 50Wliu** [comment] 2015-02-24 12:42
@roopemerikukka that's a different bug-see atom/tree-view#196.

**Comment by roopemerikukka** [comment] 2015-02-24 12:53
@50Wliu yeah but that's only how the files are shown in the tree view. My point was that if ignored files are ignored from search then unignored files should be also unignored from searches.

**Comment by 50Wliu** [comment] 2015-02-24 13:56
Sorry, I should have pointed you to a specific comment.  The bug is in libgit2, so when libgit2 fixes it, then cascaded negations should be fixed in all instances.

**Comment by simonjosefsson** [comment] 2015-03-06 15:27
Came here from google search as I suspect others did.
A toggle in the search dialog to include ignored files would be really nice

**Comment by KarlJakober** [comment] 2015-03-13 22:25
+1 for this, I dont usually search in ignored directories but sometimes I have to search through core files for my framework, would be nice to have an easy toggle rather than going through the settings panel

**Comment by freakypie** [comment] 2015-05-20 17:37
+1 can't search the "src" directory of my local virtual environment (python)

**Comment by richardwo** [comment] 2015-06-02 14:49
+1, checkbox or button required to search in hidden directories.
Like others I've had to open a different editor just to do a search in .gitignored folders

**Comment by JeffreyVdb** [comment] 2015-06-29 16:37
+1. I like the fact that you only search in your files by default, but a new keybinding to search in all files would be cool

**Comment by tillkruss** [comment] 2015-07-05 14:38
+1

**Comment by ankostyuk** [comment] 2015-07-07 06:29
+1

**Comment by benogle** [comment] 2015-07-30 22:43
You can now specify the `.gitignored` directory you want to search in the `paths` field in the editor. See atom/scandal#29 for more info

![paths](https://cloud.githubusercontent.com/assets/69169/8997016/c6b2efd4-36d1-11e5-90ec-8b6dbbfac3d0.jpg)

**Closed by benogle** 2015-07-30 22:43 UTC
Labels: enhancement

**Comment by mikebronner** [comment] 2016-03-05 17:00
Even though this topic is closed I wanted to provide some feedback, and maybe see if there have been any developments in the meanwhile. I have the "Exclude VCS Ignored Paths" checked, so that other packages, like auto-complete don't pick everything up. However, I would love to be able to over-ride that setting on a package-basis. For example, when searching in a project, I want to be able to search all files in the project, even the hidden. Could this be added as a plugin setting? Thanks!

**Comment by jcollum** [comment] 2016-12-25 18:18
@mikebronner I found that @benogle's suggestion [worked fine.](https://github.com/atom/find-and-replace/issues/207#issuecomment-126512531)  What are you proposing that wouldn't be covered by that? What's the advantage of a per-project setting? Why would it be on in some projects and off in others? 

Just asking for clarification, not trying to be argumentative, really.

**Comment by mikebronner** [comment] 2016-12-25 19:41
Its been so long :) hehe ... I think many of the plugins that were using this settings incorrectly (like autocomplete, etc.) are now working correctly, and this really hasn't been an issue for me anymore.

**Comment by dwelle** [comment] 2018-07-30 12:58
Just a note: in VSCode if you type `*` in the `files to include` when searching, it searches even in ignored files. Would be great if Atom supported this also.

Particularly because you can't specify root folder so that Atom searches within ignored files that are in the project root (or maybe I'm missing something).

**Comment by SSPJ** [comment] 2018-10-23 14:04
In Ubuntu 16.04 with version 1.26.1, unchecking Exclude VCS Ignored Paths and putting `node_modules` in the box at the bottom makes no difference.

Still can't find a thing.
