### ISSUE TITLE
find-in-project positions cursor at end of file when opening result file

### ISSUE THREAD

**Issue by ianwremmel** [atom/find-and-replace#528] opened 2015-09-17 17:52 UTC
OS Version: 
Atom Version: 1.0.11
find-and-replace Version: 0.180.0

When clicking on a search result, the file containing the result is not open, my cursor is positioned at the end of the file instead of at the position of the search result.

I've tried disabling all community plugins and the same result occurs.

**Comment by lee-dohm** [comment] 2015-09-20 05:06
I attempted to reproduce this using Atom v1.2.0-dev-ca39c10 on Mac OS X 10.10.5 and was unable to. Can you give us any more information about how this happens?

I tried:

* Single-clicking on the result
* Double-clicking on the result
* Clicking on the word searched for
* Clicking on the line number of the result
* Clicking either before or after the word searched for in the result

None of them would end in the behavior you specify.

**Comment by ianwremmel** [comment] 2015-09-20 17:25
Hmm, interesting. I thought I had been seeing it consistently, but when I went to reproduce it, it didn't happen to all search results. That said, here's a video where I search a project and click one of the results does have the problem.

![out](https://cloud.githubusercontent.com/assets/1182361/9981997/c3f816ec-5f81-11e5-8699-4f0dc88fa533.gif)

**Comment by jrouviere** [comment] 2015-09-21 10:21
I've also been experiencing this issue for the last couple of releases (or maybe since I upgraded to OS X beta?).
The problem only occurs when the file was not previously opened. It seems like the file is opened at the correct position but the editor immediately scroll to end of file. When the file is already opened it works as expected though.

OS Version: OS X 10.11
Atom Version: 1.0.15
Find and replace: 0.181.0

**Comment by lee-dohm** [comment] 2015-09-21 15:41
I thought it might have something to do with the find results being opened in the right pane. I still can't reproduce this using Atom v1.2.0-dev-abccf81 on Mac OS X 10.10.5. I also made sure that it was opening new files. That doesn't reproduce it either.

@ianwremmel Are you on OS X 10.11 also?

**Comment by ianwremmel** [comment] 2015-09-21 15:43
I'm on 10.10

**Comment by iskeld** [comment] 2015-10-01 12:35
I'm having the same issue on Atom 1.0.19 / Windows. But I found out that it's the editorconfig package that is causing the problem. @ianwremmel @jrouviere - do you have this package enabled? There is open issue in this package repo: https://github.com/sindresorhus/atom-editorconfig/issues/51

**Comment by jrouviere** [comment] 2015-10-01 12:42
@iskeld Yes correct, I do have the editorconfig package installed.

**Comment by ianwremmel** [comment] 2015-10-02 16:41
Yep, I also have editorconfig installed. I'll try disabling it and report back if I continue to see the issue.

**Comment by 50Wliu** [comment] 2015-10-02 19:45
Ok, so this issue seems to be caused by editorconfig (just had another report on Slack that was resolved after disabling it - /cc @sdornan), so closing this out.

**Closed by 50Wliu** 2015-10-02 19:45 UTC
Labels: needs-reproduction
