### ISSUE TITLE
Find in project overwrites find text when match is selected in buffer from results

### ISSUE THREAD

**Issue by bblack** [atom/find-and-replace#366] opened 2015-03-18 20:07 UTC
To reproduce:

1. Shift+command+f to bring up the 'find in project" pane
2. Ensure the regex option is selected
3. Search for a regex that includes a backslash (e.g. `console\.log`)
4. Click any result to go to the file in which it appears
5. Press shift+command+f again.

The backslash has disappeared from the input field. It now says `console.log`.

This has been present in atom for me for months, as long as I can remember. I just reproduced this with `--safe`.

Mac OSX, Atom 0.186.0

Copied from https://github.com/atom/atom/issues/5887

**Comment by benogle** [comment] 2015-03-18 20:14
We found the root cause, right? `Backslashes disappear from "find in project"` is not really the correct description. This is what happens:

* search in project
* click a result
* that result is highlighted
* cmd-shift-f populates the find box with the selected text, replacing the regex.

**Comment by izuzak** [comment] 2015-07-31 09:06
@benogle I think we can close this as well, because I think it is a duplicate of https://github.com/atom/find-and-replace/issues/455. If you try following the reproduction steps in the issue description above -- you won't be able to reproduce because now the package escapes strings used for search when the regex options is turned on (and that wasn't the case before).

**Comment by izuzak** [comment] 2015-07-31 09:09
Or would we consider changing how the package works so that clicking a result from project search and then pressing shift+cmd+f doesn't touch the current search term at all?

**Comment by benogle** [comment] 2015-07-31 19:05
> Or would we consider changing how the package works so that clicking a result from project search and then pressing shift+cmd+f doesn't touch the current search term at all?

That seems like it requires keeping a lot of state, and maybe confusing UX. I think it be predictable in always replacing the pattern with the selection.

Closing as a dupe of #455

**Closed by benogle** 2015-07-31 19:05 UTC
Labels: enhancement
