### ISSUE TITLE
Find Next / Previous Missing

### ISSUE THREAD

**Issue by davidbarratt** [atom/find-and-replace#337] opened 2015-01-21 21:02 UTC
For some reason, Find Next and Find Previous are missing and have been replaced with just "Find". On my other computer (both most recent version) it is correct. What's going on?

![screen shot 2015-01-21 at 4 01 35 pm](https://cloud.githubusercontent.com/assets/868364/5845035/d9162546-a186-11e4-861f-6c91063973a9.png)

**Comment by 50Wliu** [comment] 2015-01-21 22:04
Duplicate of #322.

**Closed by 50Wliu** 2015-01-21 22:04 UTC
