### ISSUE TITLE
VCS Ignored Paths included when specifying "File/directory" pattern

### ISSUE THREAD

**Issue by surdu** [atom/find-and-replace#915] opened 2017-06-22 12:12 UTC
### Steps to Reproduce

1. Open find-and-replace
2. Fill the `File/directory pattern` field with a folder that contain a VCS ignored folder (in my case `node-modules`
3. Enter a search term that would be found in one of the files inside the VCS ignored folders
3. Press `Find all`

**Expected behavior:** 
Items in VCS folder are NOT present in the search results

**Actual behavior:** 
Items in VCS folder are ARE present in the search results

**Reproduces how often:** 
Every time

### Versions
**Atom:** 1.19.0-beta1
**find-and-replace:** 0.208.3

**Comment by rsese** [comment] 2017-06-23 01:41
Thanks for the report!

This looks like a duplicate of https://github.com/atom/find-and-replace/issues/636 so you can subscribe there for updates if you'd like.  Let me know if you think the issue is different though.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-23 01:41 UTC
