### ISSUE TITLE
No results for search using Regex in project

### ISSUE THREAD

**Issue by AlexWayfer** [atom/find-and-replace#970] opened 2017-11-07 16:08 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Search using Regex doesn't find results in project search, while in file search it does.

### Steps to Reproduce

1. Have file with something like:
```erb
<%=
	render
```
2. Search in project with Regex `<%=\n\t+render`

**Expected behavior:** Search results.

**Actual behavior:** No search results.

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.15.0
```

Arch Linux, `4.13.11-1`.

### Additional Information

![image](https://user-images.githubusercontent.com/6510020/32503651-d5529d8a-c3ee-11e7-96a7-5d8d423aae21.png)

![image](https://user-images.githubusercontent.com/6510020/32503674-e11559c8-c3ee-11e7-8728-b6a538adb55f.png)

**Comment by 50Wliu** [comment] 2017-11-07 17:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #218. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-11-07 17:38 UTC

**Comment by AlexWayfer** [comment] 2017-11-07 17:52
Thank you! Sorry, I didn't notice that it's almost the same.
