### ISSUE TITLE
`.gitignore` is not respected when doing a filtered search in a project folder

### ISSUE THREAD

**Issue by eyeballquip** [atom/find-and-replace#890] opened 2017-05-01 18:16 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With a project name added to the filter, searching via Project Find will not respect `.gitignore`'d files. Searching without the filter behaves as expected.

### Steps to Reproduce

1. Add a project folder, `folder1` that contains a `.gitignore` and an ignored directory (e.g. `node_modules`)
2. Open `Project Find`
3. Add `folder1` to the `File/directory pattern` box
4. Search for string that is present in any file matched by the `.gitignore`

**Expected behaviour:** Only results in files not matched by the `.gitignore` are returned

**Actual behaviour:** Results in all files for `folder1` are returned

**Reproduces how often:** 100%

### Versions

`Atom: 1.17.0-beta4`
`OSL: macOS Sierra 10.12.4`

**Comment by rsese** [comment] 2017-05-02 06:22
Hmm, I think this is a duplicate of https://github.com/atom/find-and-replace/issues/621?  

You mentioned adding 2 project folders in your steps to reproduce but I can reproduce with just 1 as long as I specify a directory in the project search, basically the same steps as detailed in https://github.com/atom/find-and-replace/issues/621#issuecomment-219200229.

Just to confirm, do you only see this behavior with 2 project folders or can you reproduce without your step 2?

**Comment by eyeballquip** [comment] 2017-05-02 17:58
hey @rsese. I tried again with just one folder, confirmed that is also happens in that situation.

**Comment by rsese** [comment] 2017-05-02 18:47
Great thanks for confirming - in that case, I think this is a duplicate of #636 (I edited my comment above because I referenced the wrong issue).  This comment from that issue describes the same behavior /cc https://github.com/atom/find-and-replace/issues/636#issuecomment-219200229.

You can subscribe there for update and I'll close this as a duplicate, but if I mis-understood anything, let me know.

**Closed by rsese** 2017-05-02 18:47 UTC
Labels: more-information-needed
