### ISSUE TITLE
Find and Replace does not work across Project

### ISSUE THREAD

**Issue by hansoksendahl** [atom/find-and-replace#787] opened 2016-09-29 17:50 UTC
Replacing with "Find in Project" on OSX El Capitan 10.11.6 for the following input parameters does not result in expected behavior.

Reproduction steps:

Invoke "Find in Project" [Command]+[Shift]+[F]
Select: "Use Regex"
Select: "Case Insensitive"
Search Regex: ^(\s_)(@extend._)$
Replace String: $1// $2

In my project it finds the occurence of the regex 40 times in 14 files.  When I click "Replace All" I am given a dialog which prompts:

> This will replace '^(\s_)(\@extend._)$' with '$1// $2' 40 times in 14 files.

When I click "Ok" nothing is replaced.

**NOTE** Same results for "Case insensitive" and "Case sensitive".

**Comment by mp4096** [comment] 2016-10-04 19:12
I have a similar problem with `find-and-replace 0.201.0` on Xubuntu 16.04. 
The issue seems to be quite quirky. Here's a minimal example:
1. Create a file `foo.txt` with the following contents:
```
test
test
```
2. __Keep the buffer opened.__ Project search and replace: search `^test`, replace with `hello` -> everything should be ok
3. Change the file contents back to 
```
test
test
```
4. __Now close this buffer.__ Project search and replace: search `^test`, replace with `hello` -> only the first instance of `test` is replaced with `hello`, the second one stays and will be replaced only if you open `foo.txt` again.

**Comment by mp4096** [comment] 2016-10-04 19:22
This bug also seems to be present in versions as old as `0.180.0`.

**Comment by robeeeert** [comment] 2016-11-23 10:33
This really seems to be related to the line begin / end characters (^ and $). I ran into the issue of the OP while trying to replace `= ((this\..+)(\.bind\(this\))$)` by `= ::$2`. When I changed the regex to `= ((this\..+)(\.bind\(this\)))` (removing the `$`), it performed well.

**Comment by heruan** [comment] 2016-12-07 09:30
Possibly duplicated by #788 and #808.

**Comment by heruan** [comment] 2016-12-07 09:31
I can confirm that removing the `^` or `$` works and the replace takes place.

**Comment by 50Wliu** [comment] 2016-12-07 22:53
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #622. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-07 22:53 UTC
