### ISSUE TITLE
Searching in files with encoding other than UTF-8 doesn't work

### ISSUE THREAD

**Issue by Susexe** [atom/find-and-replace#1074] opened 2019-03-14 21:07 UTC
When the default encoding in Core settings is changed (UTF-16 LE, in my case), it doesn't affect the "Find in Project" option. It seems UTF-8 is ingrained, considering Atom displays the files in UTF-8 first and then converts them to the preferred encoding (it can easily be seen when clicking through files from the Project pane).

**Comment by rsese** [comment] 2019-03-19 01:44
Thanks for the report @Susexe - can you fill out the issue template and provide step-by-step instructions to reproduce?  If you can share a test file as well, that would be useful for us.

The information in the template is super helpful for us when triaging issues.

**Comment by Susexe** [comment] 2019-03-28 18:53
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Find in project" option doesn't work with other encodings.

### Steps to Reproduce

1. Open a project and click on the "Find in Project" option. Make sure File Encoding in Settings is changed appropriately.
2. Enter a search query.

**Expected behavior:** It should return the results.

**Actual behavior:** It does not return any.

**Reproduces how often:** 100%

### Versions
Windows 10 Home x64

```
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python
git
visual studio
```
UTF-16 LE sample file is here: [Sample.zip](https://github.com/atom/find-and-replace/files/3019731/Sample.zip)

**Comment by rsese** [comment] 2019-04-05 00:54
Ahh ok, thanks @Susexe :+1:  I can reproduce with your steps and test file but I think this is close enough to a duplicate of https://github.com/atom/find-and-replace/issues/751 that we'll close in favor of that issue (we can always reopen this one if necessary).  But I'll go ahead and copy your template details over since they're really useful.

**Closed by rsese** 2019-04-05 00:54 UTC
