### ISSUE TITLE
UX: no close button

### ISSUE THREAD

**Issue by mark-hahn** [atom/find-and-replace#347] opened 2015-02-11 00:13 UTC
It is a pain to have to go to the keyboard to close the find/replace dialog and then back to the mouse, especially for those of us who use the mouse on the left. Many other atom dialogs also have this non-standard UX. I can't remember any dialogs in any other app that don't have close buttons.

**Comment by jerone** [comment] 2015-05-17 10:36
:+1: As a mostly mouse/UI/non-keyboard user, I'm missing this simple UX too.

**Comment by itsderick** [comment] 2015-05-19 22:31
I agree with this as well. 👍

I should have known but I couldn't even figure out how to close it with a keyboard until after a few seconds of fiddling around with different key bindings. Finally, a sentence showed up that said I could close it with Esc after hitting Command + Shift + F. A close button might be more helpful, or also add that sentence when it's opened with just Command + F.

Great job guys on this editor guys. 😄

**Comment by BramVanroy** [comment] 2015-06-28 12:59
I don't know if it's a habit to +1 posts that you agree with on GitHub, but I definitely +1 this. I'd like to see it implemented as it is with the JSLint package (top right):

![JSLint closing button](https://cloud.githubusercontent.com/assets/2779410/8396451/2943495e-1da6-11e5-9c78-db18c83a3ca8.PNG)

From left to right: sort lines (n/a for search), minimise pane, close pane.

**Comment by mark-hahn** [comment] 2015-06-28 17:07
> but I definitely +1 this

A +1 by itself is considered noise and not OK.  However your post is not
noise but contains information.  A slide was shown at codeconf with pages
and pages of just +1.

The Atom forum at discuss.atom.io blocks you from posting less than 10
chars (used to be 20 but I bitched).

**Comment by BramVanroy** [comment] 2015-06-28 17:19
So because my post contained information (the image) it's OK, but if I had simply posted *+1* it wouldn't? Thanks, now I know that for the future.

**Comment by joshuapack** [comment] 2016-06-03 16:11
In the latest 1.7.4, I have been unable to close the find panel with esc. Not sure if plugin issue or something else. A graphical X would help in cases like this. I have to keep it there until I have time to figure out if it is a plugin or not.

**Comment by SystemLogoff** [comment] 2016-11-13 01:35
Plus one on this.

**Comment by reggieb** [comment] 2016-12-07 22:24
+1

**Comment by tuffylock** [comment] 2016-12-16 20:33
Users should be able to use keyboard-only AND mouse-only navigation *in as many situations as possible*. 

Switching from mouse to keyboard is *just as annoying as switching from keyboard to mouse*. 

The top of the find dialog is **giant** and **practically empty**. 

There's no excuse for not having a close button.

**Comment by ovokuro** [comment] 2017-01-19 09:50
+1

**Comment by UziTech** [comment] 2017-01-23 18:03
Also, I found out the hard way, that many panels use the `esc` as a close key and when I have multiple panels open, the only way to close the find/replace panel is to hit the `esc` key and reopen any panels that I don't want to close.

**Comment by LunarGem** [comment] 2017-03-04 22:57
Just started using Atom and I think it's awesome, but I do think that it a button or _something_ to tell people how to get rid of it. I couldn't find that shortcut anywhere but Google, not even using the Ctrl + Shift + P that lets you search shortcuts. If it's not getting an X button, at least make the shortcut searchable from the application.

**Comment by jeffmcneill** [comment] 2017-04-04 00:59
There should be some kind of system to help prioritize bugs/enhancements. This UI issue counts as a bug, though fixing it would be an enhancement? In any case, it is definitely of importance (the need to fix this bug).

**Comment by 50Wliu** [comment] 2017-04-04 01:19
> There should be some kind of system to help prioritize bugs/enhancements.

We do have a system, but it is internal (in part to avoid people trying to influence said system, and to avoid having to explain why certain issues are prioritized but others aren't).

I would classify this as an enhancement and not a bug though because a close button was considered but then rejected in the initial design.  Therefore, it is an _enhancement_ to add a close button.

**Comment by UziTech** [comment] 2017-04-17 19:18
Since Atom seems reluctant to fix this issue I have created a simple package that adds a close button 

[find-and-replace-close-button](https://atom.io/packages/find-and-replace-close-button)

![image](https://cloud.githubusercontent.com/assets/97994/25101154/aff8e0c4-2378-11e7-809a-623c4a477720.png)

**Comment by gregoftheweb** [comment] 2017-04-18 04:26
@UziTech you are, as the kids these days say, cool.

I really find it hard to believe that there is ANY pushback from the Atom guys on this.  Such a great little IDE to dig the heals in on this little UI improvement is just bizarre.  So thanks.

**Comment by 50Wliu** [comment] 2017-04-18 04:48
> Such a great little IDE to dig the heals in on this little UI improvement is just bizarre.

To clarify, we're not "digging the heels in" on this issue; hence why it's still open.  If you'd like to see a close button, submit a PR.

**Comment by jeffmcneill** [comment] 2017-04-18 04:56
Praise open source and @UziTech. Best news all week!

![screen shot 2017-04-18 at 11 55 02](https://cloud.githubusercontent.com/assets/3119827/25115120/ffa9bcfa-242d-11e7-853e-b867169c66da.png)

**Comment by BramVanroy** [comment] 2017-04-20 12:08
@UziTech  Please issue that as a PR to the main find-and-replace package. For now, it's nice as a temporary fix in its own package, but it'd be great if it's simply implemented! Thanks for your time!

**Comment by UziTech** [comment] 2017-04-20 12:33
@BramVanroy I did. See #885

**Comment by 50Wliu** [comment] 2017-05-18 17:26
#885 has been merged.  Expect a close button to appear starting with Atom 1.19.0.

**Closed by 50Wliu** 2017-05-18 17:26 UTC
Labels: enhancement, ui
