### ISSUE TITLE
Stop searching when find/replace pane is hidden

### ISSUE THREAD

**Issue by mjohnsonengr** [atom/find-and-replace#593] opened 2015-11-10 15:26 UTC
While some searches slow Atom down to a halt, others at least slow it down enough that typing becomes difficult.  Given this which I know is a known and to some extent unavoidable issue, I've noticed that after performing one of those searches, pressing the "Esc" key to hide the find/replace pane at the bottom does not stop the searching.  I actually have to delete the text in the find field before searching stops.  I can tell because of the editor's speed.

**Steps to reproduce:**
*I initially found this in a 200 line typescript file with atom-typescript enabled.
I reproduced it also on a plain-text file with 10 paragraphs of [lipsum](http://www.lipsum.com/) text.
Keybindings are Windows defaults*

1. Press `Ctrl+F` to show the find/replace pane
2. Select regex (`Ctrl+Alt+/`)
3. Enter in Find: `[a-zA-Z]` (yeah this is a terrible regex that produces hundreds or thousands of results, but the idea is to slow the editor down for demonstration purposes)
4. Try to type in the document; pay attention to how much slower it is than normal
5. Press `Esc` to hide the find/replace pane
6. Try to type again; notice how it is still just as slow as in 4.  Expected: normal typing speeds
7. `Ctrl+F` to show find/replace again
8. Delete the text in the Find field
9. `Esc` to hide again
10. Type -- normal speeds again.

This really sucks if you did a find/replace in a short file and simply pressed `Esc` before moving over to a tab with a 1,000 line file where the editor slows down to a *crawl* to now re-perform the search on that file.

**Comment by benogle** [comment] 2015-11-17 00:29
Thanks for the detailed steps. The find and replace performance is currently being worked on. Closing this as a duplicate of #145

**Closed by benogle** 2015-11-17 00:29 UTC
