### ISSUE TITLE
Regex Across Lines Behaves Differently Per-File vs Project

### ISSUE THREAD

**Issue by epmatsw** [atom/find-and-replace#791] opened 2016-10-08 16:19 UTC
Pretty minimal test case.

With regex and case-insensitive turned on, search for
```
`\s*\+\s*`
```

in a project with a single file containing:
```
const Thing = OtherThing(
    prop2: MakeAThing(
        `blah` +
        `blah`
    )
)
```

If you do the search in the single file view, it will correctly highlight the 1 result. If you do the search for the project as a whole, it won't find anything.

Even more weirdly, if you then remove the spaces in front of the 2nd blah and project search, it will find the result then. And then if you change the regex, search, and then change the regex back, it goes back to not seeing the match.

Issue is reproducible in safe mode. I've got `find-and-replace@0.201.0` installed.

![Demo gif](http://i.imgur.com/xw5sqPU.gif)

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by 50Wliu** [comment] 2016-10-08 17:02
This is a duplicate of #218 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-08 17:02 UTC
