### ISSUE TITLE
Text search cannot trigger automatically when switch to another pending pane item.

### ISSUE THREAD

**Issue by yubaoquan** [atom/find-and-replace#902] opened 2017-05-23 07:12 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Text search cannot trigger automatically when switch to another pending pane item.

### Steps to Reproduce

1. Toggle the tree view (make the tree view show on the left).
2. Open a file A. (Single click the file to make it in pending mode or double click the file to make it in permanent mode are all the same, I mean this two way all will trigger the bug);
3. Command+f search some text, for example 'xxx' and get the result.
4. Single click another file B (also has content 'xxx') in the tree view so that the file is opened in pending mode.
5. See, the search pane does not find text I just searched in fileB
6. Only when I click in fileB's text area to focus it, will the search begin to work.

**Expected behavior:** The search for text 'xxx' could trigger automatically when I move to another pending file. If the text exists, update the search result.

**Actual behavior:** The search does not triggered (only shows _No results found for 'xxx'_) until I click the editor area to focus it.

**Reproduces how often:** 100%

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
OSX : Sierra 10.12.4

**Comment by rsese** [comment] 2017-05-25 18:26
Based on the discussion in https://github.com/atom/find-and-replace/issues/901, I think this is a dupe of that issue so I'll go ahead and close but let me know if you think I mis-understood anything.  Thanks for reporting!

**Closed by rsese** 2017-05-25 18:26 UTC
