### ISSUE TITLE
Global search/replace (with regex) not working

### ISSUE THREAD

**Issue by ffxsam** [atom/find-and-replace#863] opened 2017-02-20 22:11 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When doing a global regex search/replace, matches are found and replacements are confirmed visually, but the actual replace function does nothing.

### Steps to Reproduce

(in my particular case)
1. Open Find in Project.
2. Enable regex.
3. Search for: ^export default (.*)\)$
4. Find all.
5. Replace with: export default $1);
6. Hit "Replace All"

**Expected behavior:** [What you expect to happen]

I expected all the shown instances of code to be replaced.

**Actual behavior:** [What actually happens]

I was told "Nothing replaced" and my git status confirmed that.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.11.1
Mac OS 10.12.3

### Additional Information

See screen capture: 

[ScreenFlow.zip](https://github.com/atom/atom/files/784543/ScreenFlow.zip)

**Comment by 50Wliu** [comment] 2017-02-20 23:08
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #622. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-20 23:08 UTC
