### ISSUE TITLE
Case-insensitive search does not work for national accented characters

### ISSUE THREAD

**Issue by borsosl** [atom/find-and-replace#1021] opened 2018-05-14 03:44 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Case-insensitive search does not work either for accented characters with standard unicode upper-lower case pairs. Neither in non-Regex or Regex mode.

### Steps to Reproduce

1. Create a document with this content: miért MIÉRT
2. Search for miért, miÉrt, MIÉRT, MIéRT in case-insensitive mode.
3. Switch to Regex mode and repeat 2.

**Expected behavior:** [What you expect to happen]

Whatever pairs of characters are converted by "Editor: Upper/Lower Case", they should be found in case-insensitive mode with their corresponding pairs.

**Actual behavior:** [What actually happens]

Accented words are only found if accented character is typed according to the body text.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100

### Versions

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-05-14 22:16
Thanks for contributing!

I think this is a duplicate of https://github.com/atom/superstring/issues/56 which is fixed as of 1.27.0-beta0.  If things aren't fixed you in that version let me know.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-14 22:16 UTC
