### ISSUE TITLE
CMD-D fail shortly after selecting text with three-finger on trackpad of Macbook

### ISSUE THREAD

**Issue by newton108** [atom/find-and-replace#350] opened 2015-02-14 09:58 UTC
Mac OS 10.10.2
Atom 0.179.0

It will have the same symptom if selecting keyword with mouse, use CMD-D before releasing the left click.
The effect of doing so is like selecting all the text until the next same word as the one you have selected. (Shown in the gif file in the beginning)
If doing so after releasing the left click of the mouse, it will be the desired effect. (Shown in the gif file in the end)

However when using trackpad, selecting the keyword with three fingers (without push the pad down), using CMD-D immediately after releasing the fingers, the symptom above occurs. (using CMD-D 
after several seconds will be fine).

![atom-bug](https://cloud.githubusercontent.com/assets/3450659/6199250/e67cc076-b42f-11e4-962c-e5f2094ae3fa.gif)

**Comment by ThomasLee969** [comment] 2015-03-23 06:10
Same here, `cmd-d` while dragging acts strange.

OS X 10.10.2
Atom 0.187.0
find-and-replace 0.159.0

Example:
![atom1](https://cloud.githubusercontent.com/assets/7030671/6775027/f7e19d3e-d165-11e4-9049-1e40bd22e609.gif)

Expected:
![sublime](https://cloud.githubusercontent.com/assets/7030671/6775034/2ac47032-d166-11e4-938e-a1a1d3a72307.gif)

**Comment by rsese** [comment] 2017-08-29 04:09
We came across this report while investigating another issue and see that it's a duplicate of https://github.com/atom/find-and-replace/issues/520 so you can subscribe there if you'd like (h/t @Ben3eeE 🎩 ).

**Closed by rsese** 2017-08-29 04:09 UTC
Labels: bug
