### ISSUE TITLE
find-in-buffer doesn't work in the settings buffer

### ISSUE THREAD

**Issue by jeybrahms** [atom/find-and-replace#996] opened 2018-02-17 05:32 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[find-in-buffer doesn't work in the settings buffer]

### Steps to Reproduce

1. mv .atom .atom-backup (fresh install)
2. atom --safe
3. edit/preferences (to get to the settings buffer)
4. ctrl-f
5 type any search term, e.g. settings

**Expected behavior:** [the word "settings" to be found ]

**Actual behavior:** [the search box shows 'No results found for "settings"']

**Reproduces how often:** [100%]

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Ubuntu

**Comment by rsese** [comment] 2018-02-19 18:31
Thanks for contributing!

This looks like a duplicate of https://github.com/atom/settings-view/issues/394 - the issue is closed but Damien's [comment](https://github.com/atom/settings-view/issues/394#issuecomment-337797153) is still correct as far as I know.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-19 18:31 UTC
