### ISSUE TITLE
Copy, Find, Paste pastes previous value of find input

### ISSUE THREAD

**Issue by ssorallen** [atom/find-and-replace#758] opened 2016-07-19 18:15 UTC
### Prerequisites

1. Create a new TextEditor with the contents
```
foo
bar
```
1. Open `find-and-replace` <kbd>Ctrl-f</kbd>.
1. In the `find-and-replace` panel search for the text `foo`.
1. Expected and actual `foo` is found.
1. Highlight the word `bar`.
1. Press <kbd>Ctrl-c</kbd> and <kbd>Ctrl-f</kbd> in rapid succession. It helps to hold down the <kbd>Ctrl</kbd> and quickly press c and f.

**Expected:** `find-and-replace` to contain the word `bar` because that is highlighted and `find-and-replace` defaults to the highlighted value.

**Actual:** `find-and-replace` changes to the word `bar` and then back to `foo`.

### Original report
***

A muscle memory interaction I've become used to in other text editors is to select some text, copy it (cmd-c), focus find (cmd-f), and paste (cmd-v). If you do this quickly in Atom, you end up with the previous value that was in the find-and-replace input field.

1. Open find-and-replace (cmd-f)
2. Type "foo"
3. Open a file
4. Highlight some text (let's say "bar" for reproducibility)
5. *Quickly* copy, focus find, and paste (cmd-c, cmd-f, cmd-v)

I expect "bar" to be in the find-and-replace input because that's what I copied and pasted, but I reliably get "foo".

**Comment by lee-dohm** [comment] 2016-08-30 20:06
I just tried this with Atom v1.9.9 on Mac OS X 10.11.6 and was unable to reproduce the problem. Can you verify that this still happens for you? (It is possible that I'm just not doing it fast enough, I suppose.)

**Comment by ssorallen** [comment] 2016-08-30 21:38
@lee-dohm Thanks for checking, and yes this is still happening to me on Atom 1.9.9. I am on a dual-core machine, which is maybe constrained enough to reliably reproduce the problem?

cmd-c, cmd-f, cmd-v. I keep cmd pressed the whole time and quickly press c, f, v.

**Comment by iolsen** [comment] 2016-08-30 22:48
Speed seems to matter. If you're not really fast in the copy-find-paste key sequences, this doesn't happen. I'm able to repro on 1.9.9/10.11.6.

**Comment by ssorallen** [comment] 2016-08-31 00:07
@iolsen Yeah, you have to be quick. It's the same sequence I have used in other text editors and in Chrome when copying a term and searching for it on the page, which is why this still hits me frequently. I use the same pattern in multiple other applications.

**Comment by vjeux** [comment] 2016-10-14 02:06
@ssorallen do you have a consistent repro? I want to try and fix the problem and it happened to me a few times today but I can't figure out how to reproduce it now that I want to...

**Comment by Ben3eeE** [comment] 2016-10-14 06:34
https://github.com/atom/find-and-replace/issues/684 mentions you don't even have to paste to repro this bug. I have updated the steps in the body of the issue. You can verify this by checking the history in the `find-and-replace` <kbd>Ctrl-z</kbd>. The extra step of pasting seems to happen before the value gets updated since pasting adds an extra entry to the history.

**Comment by vjeux** [comment] 2016-10-14 15:43
@Ben3eeE 💯, I can now reproduce :)

**Comment by vjeux** [comment] 2016-10-14 16:14
This is the following line of code that makes it revert back to the previous one: https://github.com/atom/find-and-replace/blob/e4fca61c9ec8b339c76686c4efa76aae5e9840a1/lib/find-view.coffee#L316-L317

**Comment by vjeux** [comment] 2016-10-14 16:40
See https://github.com/atom/find-and-replace/pull/794 for a fix

**Comment by Ben3eeE** [comment] 2016-10-16 14:16
Closed via #794 thanks to @vjeux 🙇

**Closed by Ben3eeE** 2016-10-16 14:16 UTC
Labels: bug, help-wanted
