### ISSUE TITLE
Error when scrolling Project Find Results pane

### ISSUE THREAD

**Issue by GCSBOSS** [atom/find-and-replace#978] opened 2017-12-13 12:25 UTC
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom is showing erros when scrolling through "Project Find Results" pane when multiple string found.
The erros are show in the picture at the bottom.

### Steps to Reproduce
1. "Search in Directory" on any directory.
2. Find some string to make the "Project Find Results" pane to show a scrollbar.
3. Scroll (with mouse maybe) it until the end.

**Expected behavior:** Pane to scroll up and down.
**Actual behavior:** Pane scrolls up and down with some flicker and showing errors on screen.
**Reproduces how often:** Always on scroll.

### Versions
```
OS: Windows 10 with Latest Updates
Atom: 1.23.0
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0

apm  1.18.11
npm 3.10.10
node: 6.9.5 ia32
atom 1.23.0
python
git 2.6.4.windows.1
visual studio 2015
```

### Additional Information
![image](https://user-images.githubusercontent.com/11818414/33938373-6e74dc2e-dfee-11e7-9b98-46c7f32078ce.png)

**Comment by 50Wliu** [comment] 2017-12-13 14:29
Duplicate of atom/atom#16133.  We are working to get a hotfix out.

**Closed by 50Wliu** 2017-12-13 14:29 UTC
