### ISSUE TITLE
Regex in projects show several results in preview, but "replace all" do nothing

### ISSUE THREAD

**Issue by hex2010** [atom/find-and-replace#808] opened 2016-11-09 18:25 UTC
![11111](https://cloud.githubusercontent.com/assets/13978929/20149549/a8c5ebd6-a6a9-11e6-8265-6206988132ee.png)

the regexp:

```
if\s*!\((value\[[^\^\)]*)\)\s*\{\s*return\s*false\s*\}$
```

sample lines:
```swift
		if !(value["name"] <-- name ) {return false}

		if !(value["name"] --> name ) {return false}
```

**Comment by heruan** [comment] 2016-12-07 09:23
Duplicate of https://github.com/atom/find-and-replace/issues/788

**Comment by 50Wliu** [comment] 2016-12-07 22:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #622. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-07 22:52 UTC
