### ISSUE TITLE
Uncaught TypeError: _ref3.then is not a function

### ISSUE THREAD

**Issue by skylerto** [atom/find-and-replace#662] opened 2016-02-03 21:24 UTC
[Enter steps to reproduce below:]

1. open find and replace, with a lot of results
2. double click filename to expand/collapse tab

**Atom Version**: 1.6.0-dev-49776d1
**System**: Mac OS X 10.11.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.197.1

### Stack Trace

Uncaught TypeError: _ref3.then is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project/results-view.js:52

TypeError: _ref3.then is not a function
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project/results-view.js:52:23)
    at space-pen-ol.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-ol.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:28.2.0 core:copy (atom-text-editor.editor.is-focused)
     -4:27.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:27.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
 12x -4:26.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:25.6.0 core:copy (atom-text-editor.editor.is-focused)
     -3:25.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:25 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -3:24.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:57.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:56.9.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -2:56.5.0 project-find:show (atom-text-editor.editor.mini.is-focused)
     -2:55.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  3x -2:54.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:07.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:06.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 core:cancel (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by skylerto** [comment] 2016-02-03 22:17
Seems to be here:
Lines 18-29 lib/project/results-view.coffee

```coffeescript
    @on 'mousedown', '.match-result, .path', (e) =>
      @find('.selected').removeClass('selected')
      view = $(e.target).view()
      view.addClass('selected')
      if not e.ctrlKey
        if e.originalEvent?.detail is 1
          @editorPromise = view.confirm(pending: true)
        else if e.originalEvent?.detail is 2
          @editorPromise?.then (editor) =>
            editor.terminatePendingState?()
        e.preventDefault()
      @renderResults()

```

If mousedown happens twice in a certain duration it fails.

**Comment by skylerto** [comment] 2016-02-03 22:18
## Potential fix

check time between last mouse up?

**Comment by lee-dohm** [comment] 2016-02-04 21:46
Looks like this is a duplicate of https://github.com/atom/find-and-replace/issues/650. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-04 21:46 UTC
