### ISSUE TITLE
Replace All tooltip does not go away, covers buttons

### ISSUE THREAD

**Issue by beingmrkenny** [atom/find-and-replace#539] opened 2015-09-28 15:45 UTC
The Replace All tooltip, on OS X does not go away, and obscures the buttons even when the cursor hovers over it.

![replaceall](https://cloud.githubusercontent.com/assets/2005857/10140590/3ca14e72-6600-11e5-9a92-17df7aebdf23.png)

**Comment by izuzak** [comment] 2015-09-28 15:46
Thanks for the report -- looks like a duplicate of https://github.com/atom/find-and-replace/issues/501.

**Closed by izuzak** 2015-09-28 15:46 UTC
