### ISSUE TITLE
I can not search the "^", "$", "(?=pattern)" by [Find in Buffer].

### ISSUE THREAD

**Issue by think49** [atom/find-and-replace#575] opened 2015-10-28 09:52 UTC
I can not search the **"^", "$", "(?=pattern)"** by [Find in Buffer].
If you do not consume one or more characters in a search word, it does not seem to HIT to search .
Does this behavior will a bug ?

**Comment by nmat** [comment] 2015-10-28 14:45
https://github.com/atom/find-and-replace/issues/497

seems to be a duplicate of that issue.

**Comment by think49** [comment] 2015-10-28 14:56
Thanks!
I'll try to check the issue.

**Comment by 50Wliu** [comment] 2015-10-28 15:00
Closing this issue in favor of #497; thanks @nmat!

**Closed by 50Wliu** 2015-10-28 15:00 UTC
