### ISSUE TITLE
Find whole word in PHP code unable to match variables with a preceding $ sign

### ISSUE THREAD

**Issue by aurovrata** [atom/find-and-replace#1122] opened 2020-04-24 10:19 UTC
the search is able to find variables start with the word, for example searching for `$valid` will find

`$valid`
`$validation`  (highlights only `$valid` part of the word)
`$validted` (highlights only `$valid part of the word)

however, when toggling the 'whole word` option, it finds no match.

I have to use the 'regex' mode and search for '\$valid ' with a space after it.

**Comment by Arcanemagus** [comment] 2020-04-24 22:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/1121. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-04-24 22:39 UTC

**Comment by aurovrata** [comment] 2020-04-27 05:39
odd that it got submitted twice, and the numbers are concurrent, so must have something wrong with the submission process.
